import type { EmojiData } from '../types';

export const ACTIVITIES_EMOJI_DATA: EmojiData = {
  'Activities & Sports': {
    emojis: [
      { emoji: '⚽', keywords: ['soccer', 'ball', 'football', 'sport'] },
      { emoji: '🏀', keywords: ['basketball', 'ball', 'sport'] },
      { emoji: '🏈', keywords: ['football', 'american', 'sport'] },
      { emoji: '⚾', keywords: ['baseball', 'ball', 'sport'] },
      { emoji: '🥎', keywords: ['softball', 'ball', 'sport'] },
      { emoji: '🎾', keywords: ['tennis', 'ball', 'sport'] },
      { emoji: '🏐', keywords: ['volleyball', 'ball', 'sport'] },
      { emoji: '🏉', keywords: ['rugby', 'ball', 'sport'] },
      { emoji: '🥏', keywords: ['flying', 'disc', 'frisbee'] },
      { emoji: '🎱', keywords: ['pool', 'billiards', '8ball'] },
      { emoji: '🪀', keywords: ['yo-yo', 'toy'] },
      { emoji: '🏓', keywords: ['ping', 'pong', 'table tennis'] },
      { emoji: '🏸', keywords: ['badminton', 'sport'] },
      { emoji: '🏒', keywords: ['ice', 'hockey', 'sport'] },
      { emoji: '🏑', keywords: ['field', 'hockey', 'sport'] },
      { emoji: '🥍', keywords: ['lacrosse', 'sport'] },
      { emoji: '🏏', keywords: ['cricket', 'bat', 'sport'] },
      { emoji: '🪃', keywords: ['boomerang'] },
      { emoji: '🥅', keywords: ['goal', 'net'] },
      { emoji: '⛳', keywords: ['golf', 'flag', 'hole'] },
      { emoji: '🪁', keywords: ['kite'] },
      { emoji: '🏹', keywords: ['bow', 'arrow', 'archery'] },
      { emoji: '🎣', keywords: ['fishing', 'pole', 'fish'] },
      { emoji: '🤿', keywords: ['diving', 'mask', 'snorkel'] },
      { emoji: '🥊', keywords: ['boxing', 'glove', 'sport'] },
      { emoji: '🥋', keywords: ['martial', 'arts', 'karate'] },
      { emoji: '🎽', keywords: ['running', 'shirt', 'sport'] },
      { emoji: '🛹', keywords: ['skateboard'] },
      { emoji: '🛼', keywords: ['roller', 'skate'] },
      { emoji: '🛷', keywords: ['sled', 'winter'] },
      { emoji: '⛸️', keywords: ['ice', 'skate', 'winter'] },
      { emoji: '🥌', keywords: ['curling', 'stone', 'sport'] },
      { emoji: '🎿', keywords: ['ski', 'winter', 'snow'] },
      { emoji: '🎯', keywords: ['target', 'dart', 'bullseye'] },
      { emoji: '🪄', keywords: ['magic', 'wand'] },
      { emoji: '🎮', keywords: ['video', 'game', 'controller'] },
      { emoji: '🕹️', keywords: ['joystick', 'game'] },
      { emoji: '🎰', keywords: ['slot', 'machine', 'casino'] },
      { emoji: '🎲', keywords: ['dice', 'game'] },
      { emoji: '🧩', keywords: ['puzzle', 'piece', 'jigsaw'] },
      { emoji: '🧸', keywords: ['teddy', 'bear', 'toy'] },
      { emoji: '🪆', keywords: ['nesting', 'dolls', 'matryoshka'] },
      { emoji: '♠️', keywords: ['spade', 'card', 'suit'] },
      { emoji: '♥️', keywords: ['heart', 'card', 'suit'] },
      { emoji: '♦️', keywords: ['diamond', 'card', 'suit'] },
      { emoji: '♣️', keywords: ['club', 'card', 'suit'] },
      { emoji: '♟️', keywords: ['chess', 'pawn'] },
      { emoji: '🃏', keywords: ['joker', 'card'] },
      { emoji: '🀄', keywords: ['mahjong', 'red', 'dragon'] },
      { emoji: '🎴', keywords: ['flower', 'playing', 'cards'] },
      { emoji: '🎭', keywords: ['performing', 'arts', 'theater', 'drama'] },
      { emoji: '🎨', keywords: ['art', 'palette', 'paint'] },
      { emoji: '🧵', keywords: ['thread', 'sewing'] },
      { emoji: '🪡', keywords: ['sewing', 'needle'] },
      { emoji: '🧶', keywords: ['yarn', 'knitting'] },
      { emoji: '🪢', keywords: ['knot'] },
    ],
  },
  'Travel & Places': {
    emojis: [
      { emoji: '🌍', keywords: ['globe', 'earth', 'europe', 'africa', 'world'] },
      { emoji: '🌎', keywords: ['globe', 'earth', 'americas', 'world'] },
      { emoji: '🌏', keywords: ['globe', 'earth', 'asia', 'australia', 'world'] },
      { emoji: '🌐', keywords: ['globe', 'meridians', 'world', 'internet'] },
      { emoji: '🗺️', keywords: ['world', 'map'] },
      { emoji: '🧭', keywords: ['compass', 'navigation'] },
      { emoji: '🏔️', keywords: ['mountain', 'snow'] },
      { emoji: '⛰️', keywords: ['mountain'] },
      { emoji: '🌋', keywords: ['volcano'] },
      { emoji: '🗻', keywords: ['mount', 'fuji', 'mountain'] },
      { emoji: '🏕️', keywords: ['camping', 'tent'] },
      { emoji: '🏖️', keywords: ['beach', 'umbrella'] },
      { emoji: '🏜️', keywords: ['desert'] },
      { emoji: '🏝️', keywords: ['island', 'desert'] },
      { emoji: '🏞️', keywords: ['national', 'park', 'nature'] },
      { emoji: '🏟️', keywords: ['stadium'] },
      { emoji: '🏛️', keywords: ['classical', 'building'] },
      { emoji: '🏗️', keywords: ['construction', 'building'] },
      { emoji: '🧱', keywords: ['brick', 'wall'] },
      { emoji: '🪨', keywords: ['rock', 'stone'] },
      { emoji: '🪵', keywords: ['wood', 'log'] },
      { emoji: '🛖', keywords: ['hut'] },
      { emoji: '🏘️', keywords: ['houses', 'neighborhood'] },
      { emoji: '🏚️', keywords: ['derelict', 'house'] },
      { emoji: '🏠', keywords: ['house', 'home'] },
      { emoji: '🏡', keywords: ['house', 'garden', 'home'] },
      { emoji: '🏢', keywords: ['office', 'building'] },
      { emoji: '🏥', keywords: ['hospital', 'medical'] },
      { emoji: '🏦', keywords: ['bank', 'building'] },
      { emoji: '🏨', keywords: ['hotel', 'building'] },
      { emoji: '🏪', keywords: ['convenience', 'store', 'shop'] },
      { emoji: '🏫', keywords: ['school', 'building'] },
      { emoji: '🏬', keywords: ['department', 'store', 'mall'] },
      { emoji: '🏭', keywords: ['factory', 'industry'] },
      { emoji: '🏯', keywords: ['japanese', 'castle'] },
      { emoji: '🏰', keywords: ['castle', 'european'] },
      { emoji: '💒', keywords: ['wedding', 'chapel', 'church'] },
      { emoji: '🗼', keywords: ['tokyo', 'tower'] },
      { emoji: '🗽', keywords: ['statue', 'liberty', 'new york'] },
      { emoji: '⛪', keywords: ['church', 'christian'] },
      { emoji: '🕌', keywords: ['mosque', 'islam', 'muslim'] },
      { emoji: '🛕', keywords: ['hindu', 'temple'] },
      { emoji: '🕍', keywords: ['synagogue', 'jewish'] },
      { emoji: '⛩️', keywords: ['shinto', 'shrine', 'japanese'] },
      { emoji: '⛲', keywords: ['fountain'] },
      { emoji: '⛺', keywords: ['tent', 'camping'] },
      { emoji: '🌃', keywords: ['night', 'stars', 'city'] },
      { emoji: '🏙️', keywords: ['cityscape', 'city'] },
      { emoji: '🌄', keywords: ['sunrise', 'mountain'] },
      { emoji: '🌅', keywords: ['sunrise', 'sun'] },
      { emoji: '🌆', keywords: ['cityscape', 'dusk'] },
      { emoji: '🌇', keywords: ['sunset', 'city'] },
      { emoji: '🌉', keywords: ['bridge', 'night'] },
      { emoji: '🎠', keywords: ['carousel', 'horse'] },
      { emoji: '🎡', keywords: ['ferris', 'wheel'] },
      { emoji: '🎢', keywords: ['roller', 'coaster'] },
      { emoji: '🚂', keywords: ['locomotive', 'train', 'steam'] },
      { emoji: '🚄', keywords: ['high-speed', 'train'] },
      { emoji: '🚅', keywords: ['bullet', 'train'] },
      { emoji: '🚆', keywords: ['train'] },
      { emoji: '🚇', keywords: ['metro', 'subway'] },
      { emoji: '🚌', keywords: ['bus'] },
      { emoji: '🚑', keywords: ['ambulance', 'medical'] },
      { emoji: '🚒', keywords: ['fire', 'engine', 'truck'] },
      { emoji: '🚓', keywords: ['police', 'car'] },
      { emoji: '🚕', keywords: ['taxi', 'cab'] },
      { emoji: '🚗', keywords: ['car', 'automobile', 'vehicle'] },
      { emoji: '🚙', keywords: ['suv', 'car', 'sport'] },
      { emoji: '🛻', keywords: ['pickup', 'truck'] },
      { emoji: '🚚', keywords: ['delivery', 'truck'] },
      { emoji: '🚜', keywords: ['tractor', 'farm'] },
      { emoji: '🏎️', keywords: ['racing', 'car', 'formula'] },
      { emoji: '🏍️', keywords: ['motorcycle', 'racing'] },
      { emoji: '🛵', keywords: ['motor', 'scooter'] },
      { emoji: '🚲', keywords: ['bicycle', 'bike'] },
      { emoji: '🛴', keywords: ['kick', 'scooter'] },
      { emoji: '⛽', keywords: ['fuel', 'pump', 'gas'] },
      { emoji: '🚨', keywords: ['police', 'light', 'emergency'] },
      { emoji: '🚥', keywords: ['traffic', 'light'] },
      { emoji: '🚧', keywords: ['construction', 'barrier'] },
      { emoji: '⚓', keywords: ['anchor', 'ship'] },
      { emoji: '⛵', keywords: ['sailboat', 'boat'] },
      { emoji: '🚤', keywords: ['speedboat', 'boat'] },
      { emoji: '🛳️', keywords: ['passenger', 'ship'] },
      { emoji: '🚢', keywords: ['ship', 'boat'] },
      { emoji: '✈️', keywords: ['airplane', 'plane', 'flight'] },
      { emoji: '🛫', keywords: ['airplane', 'departure', 'takeoff'] },
      { emoji: '🛬', keywords: ['airplane', 'arrival', 'landing'] },
      { emoji: '🪂', keywords: ['parachute'] },
      { emoji: '💺', keywords: ['seat', 'chair'] },
      { emoji: '🚁', keywords: ['helicopter'] },
      { emoji: '🛰️', keywords: ['satellite', 'space'] },
      { emoji: '🚀', keywords: ['rocket', 'space', 'launch'] },
      { emoji: '🛸', keywords: ['flying', 'saucer', 'ufo'] },
    ],
  },
};
