import type { EmojiData } from '../types';

export const ANIMALS_NATURE_EMOJI_DATA: EmojiData = {
  'Animals & Nature': {
    emojis: [
      { emoji: '🐶', keywords: ['dog', 'face', 'puppy', 'pet'] },
      { emoji: '🐕', keywords: ['dog', 'pet'] },
      { emoji: '🦮', keywords: ['guide', 'dog', 'service'] },
      { emoji: '🐩', keywords: ['poodle', 'dog'] },
      { emoji: '🐺', keywords: ['wolf', 'face'] },
      { emoji: '🦊', keywords: ['fox', 'face'] },
      { emoji: '🦝', keywords: ['raccoon'] },
      { emoji: '🐱', keywords: ['cat', 'face', 'pet', 'kitten'] },
      { emoji: '🐈', keywords: ['cat', 'pet'] },
      { emoji: '🦁', keywords: ['lion', 'face', 'king'] },
      { emoji: '🐯', keywords: ['tiger', 'face'] },
      { emoji: '🐅', keywords: ['tiger'] },
      { emoji: '🐆', keywords: ['leopard', 'spots'] },
      { emoji: '🐴', keywords: ['horse', 'face'] },
      { emoji: '🐎', keywords: ['horse', 'racing'] },
      { emoji: '🦄', keywords: ['unicorn', 'face', 'magic'] },
      { emoji: '🦓', keywords: ['zebra', 'stripes'] },
      { emoji: '🦌', keywords: ['deer'] },
      { emoji: '🦬', keywords: ['bison', 'buffalo'] },
      { emoji: '🐮', keywords: ['cow', 'face'] },
      { emoji: '🐂', keywords: ['ox', 'bull'] },
      { emoji: '🐃', keywords: ['water', 'buffalo'] },
      { emoji: '🐄', keywords: ['cow', 'dairy'] },
      { emoji: '🐷', keywords: ['pig', 'face'] },
      { emoji: '🐖', keywords: ['pig'] },
      { emoji: '🐗', keywords: ['boar', 'wild', 'pig'] },
      { emoji: '🐽', keywords: ['pig', 'nose'] },
      { emoji: '🐏', keywords: ['ram', 'sheep'] },
      { emoji: '🐑', keywords: ['sheep', 'ewe'] },
      { emoji: '🐐', keywords: ['goat'] },
      { emoji: '🐪', keywords: ['camel', 'one', 'hump'] },
      { emoji: '🐫', keywords: ['camel', 'two', 'humps'] },
      { emoji: '🦙', keywords: ['llama', 'alpaca'] },
      { emoji: '🦒', keywords: ['giraffe'] },
      { emoji: '🐘', keywords: ['elephant'] },
      { emoji: '🦣', keywords: ['mammoth', 'woolly'] },
      { emoji: '🦏', keywords: ['rhinoceros', 'rhino'] },
      { emoji: '🦛', keywords: ['hippopotamus', 'hippo'] },
      { emoji: '🐭', keywords: ['mouse', 'face'] },
      { emoji: '🐁', keywords: ['mouse'] },
      { emoji: '🐀', keywords: ['rat'] },
      { emoji: '🐹', keywords: ['hamster', 'face', 'pet'] },
      { emoji: '🐰', keywords: ['rabbit', 'face', 'bunny'] },
      { emoji: '🐇', keywords: ['rabbit', 'bunny'] },
      { emoji: '🐿️', keywords: ['chipmunk', 'squirrel'] },
      { emoji: '🦫', keywords: ['beaver'] },
      { emoji: '🦔', keywords: ['hedgehog'] },
      { emoji: '🦇', keywords: ['bat'] },
      { emoji: '🐻', keywords: ['bear', 'face'] },
      { emoji: '🐨', keywords: ['koala', 'face'] },
      { emoji: '🐼', keywords: ['panda', 'face'] },
      { emoji: '🦥', keywords: ['sloth'] },
      { emoji: '🦦', keywords: ['otter'] },
      { emoji: '🦨', keywords: ['skunk'] },
      { emoji: '🦘', keywords: ['kangaroo'] },
      { emoji: '🦡', keywords: ['badger'] },
      { emoji: '🐾', keywords: ['paw', 'prints', 'pet'] },
      { emoji: '🦃', keywords: ['turkey'] },
      { emoji: '🐔', keywords: ['chicken', 'hen'] },
      { emoji: '🐓', keywords: ['rooster', 'cock'] },
      { emoji: '🐣', keywords: ['hatching', 'chick', 'egg'] },
      { emoji: '🐤', keywords: ['baby', 'chick'] },
      { emoji: '🐥', keywords: ['front', 'facing', 'chick'] },
      { emoji: '🐦', keywords: ['bird'] },
      { emoji: '🐧', keywords: ['penguin'] },
      { emoji: '🕊️', keywords: ['dove', 'peace'] },
      { emoji: '🦅', keywords: ['eagle', 'bird'] },
      { emoji: '🦆', keywords: ['duck'] },
      { emoji: '🦢', keywords: ['swan'] },
      { emoji: '🦉', keywords: ['owl'] },
      { emoji: '🦤', keywords: ['dodo', 'extinct'] },
      { emoji: '🪶', keywords: ['feather', 'bird'] },
      { emoji: '🦩', keywords: ['flamingo', 'pink'] },
      { emoji: '🦚', keywords: ['peacock'] },
      { emoji: '🦜', keywords: ['parrot'] },
      { emoji: '🐸', keywords: ['frog', 'face'] },
      { emoji: '🐊', keywords: ['crocodile', 'alligator'] },
      { emoji: '🐢', keywords: ['turtle', 'tortoise'] },
      { emoji: '🦎', keywords: ['lizard', 'reptile'] },
      { emoji: '🐍', keywords: ['snake'] },
      { emoji: '🐲', keywords: ['dragon', 'face'] },
      { emoji: '🐉', keywords: ['dragon'] },
      { emoji: '🦕', keywords: ['dinosaur', 'sauropod'] },
      { emoji: '🦖', keywords: ['dinosaur', 't-rex'] },
      { emoji: '🐳', keywords: ['whale', 'spouting'] },
      { emoji: '🐋', keywords: ['whale'] },
      { emoji: '🐬', keywords: ['dolphin', 'flipper'] },
      { emoji: '🦭', keywords: ['seal'] },
      { emoji: '🐟', keywords: ['fish'] },
      { emoji: '🐠', keywords: ['tropical', 'fish'] },
      { emoji: '🐡', keywords: ['blowfish', 'pufferfish'] },
      { emoji: '🦈', keywords: ['shark'] },
      { emoji: '🐙', keywords: ['octopus'] },
      { emoji: '🐚', keywords: ['shell', 'beach'] },
      { emoji: '🐌', keywords: ['snail'] },
      { emoji: '🦋', keywords: ['butterfly'] },
      { emoji: '🐛', keywords: ['bug', 'caterpillar'] },
      { emoji: '🐜', keywords: ['ant', 'insect'] },
      { emoji: '🐝', keywords: ['bee', 'honeybee'] },
      { emoji: '🪲', keywords: ['beetle', 'bug'] },
      { emoji: '🐞', keywords: ['ladybug', 'ladybird'] },
      { emoji: '🦗', keywords: ['cricket', 'grasshopper'] },
      { emoji: '🪳', keywords: ['cockroach', 'bug'] },
      { emoji: '🕷️', keywords: ['spider'] },
      { emoji: '🕸️', keywords: ['spider', 'web'] },
      { emoji: '🦂', keywords: ['scorpion'] },
      { emoji: '🦟', keywords: ['mosquito'] },
      { emoji: '🪰', keywords: ['fly', 'insect'] },
      { emoji: '🪱', keywords: ['worm'] },
      { emoji: '🦠', keywords: ['microbe', 'germ', 'virus', 'bacteria'] },
    ],
  },
  'Plants & Flowers': {
    emojis: [
      { emoji: '💐', keywords: ['bouquet', 'flowers'] },
      { emoji: '🌸', keywords: ['cherry', 'blossom', 'flower', 'pink'] },
      { emoji: '💮', keywords: ['white', 'flower'] },
      { emoji: '🏵️', keywords: ['rosette', 'flower'] },
      { emoji: '🌹', keywords: ['rose', 'flower', 'red', 'love'] },
      { emoji: '🥀', keywords: ['wilted', 'flower', 'dead'] },
      { emoji: '🌺', keywords: ['hibiscus', 'flower'] },
      { emoji: '🌻', keywords: ['sunflower', 'flower', 'yellow'] },
      { emoji: '🌼', keywords: ['blossom', 'flower', 'yellow'] },
      { emoji: '🌷', keywords: ['tulip', 'flower'] },
      { emoji: '🌱', keywords: ['seedling', 'plant', 'grow'] },
      { emoji: '🪴', keywords: ['potted', 'plant'] },
      { emoji: '🌲', keywords: ['evergreen', 'tree', 'pine'] },
      { emoji: '🌳', keywords: ['deciduous', 'tree'] },
      { emoji: '🌴', keywords: ['palm', 'tree', 'tropical'] },
      { emoji: '🌵', keywords: ['cactus', 'desert'] },
      { emoji: '🌾', keywords: ['rice', 'sheaf', 'grain', 'wheat'] },
      { emoji: '🌿', keywords: ['herb', 'leaf', 'green'] },
      { emoji: '☘️', keywords: ['shamrock', 'clover', 'irish'] },
      { emoji: '🍀', keywords: ['four', 'leaf', 'clover', 'lucky'] },
      { emoji: '🍁', keywords: ['maple', 'leaf', 'fall', 'canada'] },
      { emoji: '🍂', keywords: ['fallen', 'leaf', 'autumn'] },
      { emoji: '🍃', keywords: ['leaf', 'fluttering', 'wind'] },
      { emoji: '🪹', keywords: ['empty', 'nest'] },
      { emoji: '🪺', keywords: ['nest', 'eggs'] },
    ],
  },
};
