import type { EmojiData } from '../types';

export const FOOD_EMOJI_DATA: EmojiData = {
  'Food & Drink': {
    emojis: [
      { emoji: '🍇', keywords: ['grapes', 'fruit', 'wine'] },
      { emoji: '🍈', keywords: ['melon', 'fruit'] },
      { emoji: '🍉', keywords: ['watermelon', 'fruit', 'summer'] },
      { emoji: '🍊', keywords: ['tangerine', 'orange', 'fruit'] },
      { emoji: '🍋', keywords: ['lemon', 'fruit', 'sour'] },
      { emoji: '🍌', keywords: ['banana', 'fruit'] },
      { emoji: '🍍', keywords: ['pineapple', 'fruit'] },
      { emoji: '🥭', keywords: ['mango', 'fruit', 'tropical'] },
      { emoji: '🍎', keywords: ['apple', 'red', 'fruit'] },
      { emoji: '🍏', keywords: ['apple', 'green', 'fruit'] },
      { emoji: '🍐', keywords: ['pear', 'fruit'] },
      { emoji: '🍑', keywords: ['peach', 'fruit'] },
      { emoji: '🍒', keywords: ['cherries', 'fruit'] },
      { emoji: '🍓', keywords: ['strawberry', 'fruit', 'berry'] },
      { emoji: '🫐', keywords: ['blueberries', 'fruit', 'berry'] },
      { emoji: '🥝', keywords: ['kiwi', 'fruit'] },
      { emoji: '🍅', keywords: ['tomato', 'vegetable', 'fruit'] },
      { emoji: '🫒', keywords: ['olive'] },
      { emoji: '🥥', keywords: ['coconut', 'tropical'] },
      { emoji: '🥑', keywords: ['avocado', 'fruit'] },
      { emoji: '🍆', keywords: ['eggplant', 'aubergine', 'vegetable'] },
      { emoji: '🥔', keywords: ['potato', 'vegetable'] },
      { emoji: '🥕', keywords: ['carrot', 'vegetable', 'orange'] },
      { emoji: '🌽', keywords: ['corn', 'maize', 'vegetable'] },
      { emoji: '🌶️', keywords: ['pepper', 'hot', 'chili', 'spicy'] },
      { emoji: '🫑', keywords: ['bell', 'pepper', 'vegetable'] },
      { emoji: '🥒', keywords: ['cucumber', 'vegetable'] },
      { emoji: '🥬', keywords: ['leafy', 'green', 'vegetable', 'lettuce'] },
      { emoji: '🥦', keywords: ['broccoli', 'vegetable'] },
      { emoji: '🧄', keywords: ['garlic', 'vegetable'] },
      { emoji: '🧅', keywords: ['onion', 'vegetable'] },
      { emoji: '🍄', keywords: ['mushroom', 'fungus'] },
      { emoji: '🥜', keywords: ['peanuts', 'nuts'] },
      { emoji: '🫘', keywords: ['beans'] },
      { emoji: '🌰', keywords: ['chestnut', 'nut'] },
      { emoji: '🍞', keywords: ['bread', 'loaf'] },
      { emoji: '🥐', keywords: ['croissant', 'french', 'pastry'] },
      { emoji: '🥖', keywords: ['baguette', 'french', 'bread'] },
      { emoji: '🫓', keywords: ['flatbread'] },
      { emoji: '🥨', keywords: ['pretzel', 'snack'] },
      { emoji: '🥯', keywords: ['bagel', 'bread'] },
      { emoji: '🥞', keywords: ['pancakes', 'breakfast'] },
      { emoji: '🧇', keywords: ['waffle', 'breakfast'] },
      { emoji: '🧀', keywords: ['cheese', 'dairy'] },
      { emoji: '🍖', keywords: ['meat', 'bone'] },
      { emoji: '🍗', keywords: ['poultry', 'leg', 'chicken'] },
      { emoji: '🥩', keywords: ['steak', 'meat', 'beef'] },
      { emoji: '🥓', keywords: ['bacon', 'meat'] },
      { emoji: '🍔', keywords: ['hamburger', 'burger', 'fast food'] },
      { emoji: '🍟', keywords: ['fries', 'french', 'fast food'] },
      { emoji: '🍕', keywords: ['pizza', 'italian'] },
      { emoji: '🌭', keywords: ['hot dog', 'sausage'] },
      { emoji: '🥪', keywords: ['sandwich'] },
      { emoji: '🌮', keywords: ['taco', 'mexican'] },
      { emoji: '🌯', keywords: ['burrito', 'mexican'] },
      { emoji: '🫔', keywords: ['tamale', 'mexican'] },
      { emoji: '🥙', keywords: ['pita', 'falafel', 'kebab'] },
      { emoji: '🧆', keywords: ['falafel'] },
      { emoji: '🥚', keywords: ['egg'] },
      { emoji: '🍳', keywords: ['cooking', 'egg', 'fried', 'breakfast'] },
      { emoji: '🥘', keywords: ['paella', 'pan', 'food'] },
      { emoji: '🍲', keywords: ['pot', 'food', 'stew'] },
      { emoji: '🫕', keywords: ['fondue'] },
      { emoji: '🥣', keywords: ['bowl', 'spoon', 'cereal'] },
      { emoji: '🥗', keywords: ['salad', 'green', 'healthy'] },
      { emoji: '🍿', keywords: ['popcorn', 'movie', 'snack'] },
      { emoji: '🧈', keywords: ['butter', 'dairy'] },
      { emoji: '🧂', keywords: ['salt', 'seasoning'] },
      { emoji: '🥫', keywords: ['canned', 'food'] },
      { emoji: '🍱', keywords: ['bento', 'box', 'japanese'] },
      { emoji: '🍘', keywords: ['rice', 'cracker', 'japanese'] },
      { emoji: '🍙', keywords: ['rice', 'ball', 'japanese', 'onigiri'] },
      { emoji: '🍚', keywords: ['rice', 'cooked'] },
      { emoji: '🍛', keywords: ['curry', 'rice', 'indian'] },
      { emoji: '🍜', keywords: ['noodles', 'ramen', 'soup'] },
      { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'italian'] },
      { emoji: '🍠', keywords: ['sweet', 'potato', 'roasted'] },
      { emoji: '🍢', keywords: ['oden', 'japanese', 'skewer'] },
      { emoji: '🍣', keywords: ['sushi', 'japanese'] },
      { emoji: '🍤', keywords: ['shrimp', 'fried', 'tempura'] },
      { emoji: '🍥', keywords: ['fish', 'cake', 'narutomaki'] },
      { emoji: '🥮', keywords: ['moon', 'cake', 'chinese'] },
      { emoji: '🍡', keywords: ['dango', 'japanese', 'dessert'] },
      { emoji: '🥟', keywords: ['dumpling', 'asian'] },
      { emoji: '🥠', keywords: ['fortune', 'cookie'] },
      { emoji: '🥡', keywords: ['takeout', 'box', 'chinese'] },
      { emoji: '🦀', keywords: ['crab', 'seafood'] },
      { emoji: '🦞', keywords: ['lobster', 'seafood'] },
      { emoji: '🦐', keywords: ['shrimp', 'prawn', 'seafood'] },
      { emoji: '🦑', keywords: ['squid', 'seafood'] },
      { emoji: '🦪', keywords: ['oyster', 'seafood'] },
      { emoji: '🍦', keywords: ['ice', 'cream', 'soft', 'serve', 'dessert'] },
      { emoji: '🍧', keywords: ['shaved', 'ice', 'dessert'] },
      { emoji: '🍨', keywords: ['ice', 'cream', 'dessert'] },
      { emoji: '🍩', keywords: ['doughnut', 'donut', 'dessert'] },
      { emoji: '🍪', keywords: ['cookie', 'dessert', 'biscuit'] },
      { emoji: '🎂', keywords: ['birthday', 'cake', 'dessert'] },
      { emoji: '🍰', keywords: ['cake', 'slice', 'dessert', 'shortcake'] },
      { emoji: '🧁', keywords: ['cupcake', 'dessert'] },
      { emoji: '🥧', keywords: ['pie', 'dessert'] },
      { emoji: '🍫', keywords: ['chocolate', 'bar', 'dessert'] },
      { emoji: '🍬', keywords: ['candy', 'sweet'] },
      { emoji: '🍭', keywords: ['lollipop', 'candy'] },
      { emoji: '🍮', keywords: ['custard', 'pudding', 'flan', 'dessert'] },
      { emoji: '🍯', keywords: ['honey', 'pot'] },
      { emoji: '🍼', keywords: ['baby', 'bottle', 'milk'] },
      { emoji: '🥛', keywords: ['milk', 'glass', 'dairy'] },
      { emoji: '☕', keywords: ['coffee', 'hot', 'drink', 'cafe'] },
      { emoji: '🫖', keywords: ['teapot'] },
      { emoji: '🍵', keywords: ['tea', 'green', 'matcha', 'drink'] },
      { emoji: '🍶', keywords: ['sake', 'japanese', 'drink'] },
      { emoji: '🍾', keywords: ['champagne', 'bottle', 'celebration'] },
      { emoji: '🍷', keywords: ['wine', 'glass', 'drink'] },
      { emoji: '🍸', keywords: ['cocktail', 'glass', 'martini', 'drink'] },
      { emoji: '🍹', keywords: ['tropical', 'drink', 'cocktail'] },
      { emoji: '🍺', keywords: ['beer', 'mug', 'drink'] },
      { emoji: '🍻', keywords: ['beer', 'cheers', 'mugs', 'drink'] },
      { emoji: '🥂', keywords: ['champagne', 'glasses', 'toast', 'cheers'] },
      { emoji: '🥃', keywords: ['whisky', 'glass', 'tumbler', 'drink'] },
      { emoji: '🥤', keywords: ['cup', 'straw', 'soda', 'drink'] },
      { emoji: '🧋', keywords: ['bubble', 'tea', 'boba', 'drink'] },
      { emoji: '🧃', keywords: ['juice', 'box', 'drink'] },
      { emoji: '🧉', keywords: ['mate', 'drink'] },
      { emoji: '🧊', keywords: ['ice', 'cube'] },
      { emoji: '🥢', keywords: ['chopsticks', 'asian'] },
      { emoji: '🍽️', keywords: ['plate', 'cutlery', 'dining'] },
      { emoji: '🍴', keywords: ['fork', 'knife', 'cutlery'] },
      { emoji: '🥄', keywords: ['spoon'] },
    ],
  },
};
