import type { EmojiData } from '../types';

export const OBJECTS_EMOJI_DATA: EmojiData = {
  Objects: {
    emojis: [
      { emoji: '⌚', keywords: ['watch', 'time'] },
      { emoji: '📱', keywords: ['mobile', 'phone', 'smartphone', 'cell'] },
      { emoji: '💻', keywords: ['laptop', 'computer'] },
      { emoji: '⌨️', keywords: ['keyboard', 'computer'] },
      { emoji: '🖥️', keywords: ['desktop', 'computer', 'monitor'] },
      { emoji: '🖨️', keywords: ['printer'] },
      { emoji: '🖱️', keywords: ['mouse', 'computer'] },
      { emoji: '💽', keywords: ['minidisc', 'disk'] },
      { emoji: '💾', keywords: ['floppy', 'disk', 'save'] },
      { emoji: '💿', keywords: ['cd', 'optical', 'disk'] },
      { emoji: '📀', keywords: ['dvd', 'disk'] },
      { emoji: '🧮', keywords: ['abacus', 'calculate'] },
      { emoji: '🎥', keywords: ['movie', 'camera', 'film'] },
      { emoji: '📺', keywords: ['television', 'tv'] },
      { emoji: '📷', keywords: ['camera', 'photo'] },
      { emoji: '📹', keywords: ['video', 'camera'] },
      { emoji: '📼', keywords: ['videocassette', 'vhs'] },
      { emoji: '🔍', keywords: ['magnifying', 'glass', 'search'] },
      { emoji: '🔎', keywords: ['magnifying', 'glass', 'search'] },
      { emoji: '🕯️', keywords: ['candle', 'light'] },
      { emoji: '💡', keywords: ['lightbulb', 'idea', 'light'] },
      { emoji: '🔦', keywords: ['flashlight', 'torch'] },
      { emoji: '🏮', keywords: ['lantern', 'red', 'paper'] },
      { emoji: '📔', keywords: ['notebook', 'decorative'] },
      { emoji: '📕', keywords: ['book', 'closed', 'red'] },
      { emoji: '📖', keywords: ['book', 'open'] },
      { emoji: '📗', keywords: ['book', 'green'] },
      { emoji: '📘', keywords: ['book', 'blue'] },
      { emoji: '📙', keywords: ['book', 'orange'] },
      { emoji: '📚', keywords: ['books', 'library', 'stack'] },
      { emoji: '📓', keywords: ['notebook'] },
      { emoji: '📃', keywords: ['page', 'curl', 'document'] },
      { emoji: '📜', keywords: ['scroll', 'document'] },
      { emoji: '📄', keywords: ['page', 'document'] },
      { emoji: '📰', keywords: ['newspaper', 'news'] },
      { emoji: '🔖', keywords: ['bookmark'] },
      { emoji: '🏷️', keywords: ['label', 'tag'] },
      { emoji: '💰', keywords: ['money', 'bag', 'dollar'] },
      { emoji: '🪙', keywords: ['coin'] },
      { emoji: '💵', keywords: ['dollar', 'banknote', 'money'] },
      { emoji: '💸', keywords: ['money', 'wings', 'flying'] },
      { emoji: '💳', keywords: ['credit', 'card', 'payment'] },
      { emoji: '🧾', keywords: ['receipt'] },
      { emoji: '✉️', keywords: ['envelope', 'mail', 'letter'] },
      { emoji: '📧', keywords: ['email', 'e-mail'] },
      { emoji: '📦', keywords: ['package', 'box', 'parcel'] },
      { emoji: '📫', keywords: ['mailbox'] },
      { emoji: '📮', keywords: ['postbox', 'mailbox'] },
      { emoji: '✏️', keywords: ['pencil', 'write'] },
      { emoji: '✒️', keywords: ['pen', 'nib', 'black'] },
      { emoji: '🖋️', keywords: ['pen', 'fountain'] },
      { emoji: '🖊️', keywords: ['pen', 'ballpoint'] },
      { emoji: '🖌️', keywords: ['paintbrush', 'brush'] },
      { emoji: '🖍️', keywords: ['crayon'] },
      { emoji: '📝', keywords: ['memo', 'pencil', 'note', 'write'] },
      { emoji: '📁', keywords: ['folder', 'file'] },
      { emoji: '📂', keywords: ['folder', 'open', 'file'] },
      { emoji: '📅', keywords: ['calendar', 'date'] },
      { emoji: '📆', keywords: ['calendar', 'tear-off'] },
      { emoji: '📇', keywords: ['card', 'index', 'rolodex'] },
      { emoji: '📈', keywords: ['chart', 'increasing', 'graph', 'growth'] },
      { emoji: '📉', keywords: ['chart', 'decreasing', 'graph', 'loss'] },
      { emoji: '📊', keywords: ['bar', 'chart', 'graph'] },
      { emoji: '📋', keywords: ['clipboard'] },
      { emoji: '📌', keywords: ['pushpin', 'pin'] },
      { emoji: '📍', keywords: ['pin', 'round', 'location'] },
      { emoji: '📎', keywords: ['paperclip', 'clip'] },
      { emoji: '📏', keywords: ['ruler', 'straight'] },
      { emoji: '📐', keywords: ['ruler', 'triangular'] },
      { emoji: '✂️', keywords: ['scissors', 'cut'] },
      { emoji: '🗑️', keywords: ['wastebasket', 'trash', 'bin'] },
      { emoji: '🔒', keywords: ['lock', 'locked', 'secure'] },
      { emoji: '🔓', keywords: ['lock', 'unlocked', 'open'] },
      { emoji: '🔐', keywords: ['lock', 'key', 'closed'] },
      { emoji: '🔑', keywords: ['key'] },
      { emoji: '🗝️', keywords: ['key', 'old'] },
      { emoji: '🔨', keywords: ['hammer', 'tool'] },
      { emoji: '🪓', keywords: ['axe', 'tool'] },
      { emoji: '⛏️', keywords: ['pick', 'mining'] },
      { emoji: '🛠️', keywords: ['hammer', 'wrench', 'tools'] },
      { emoji: '🗡️', keywords: ['dagger', 'knife', 'sword'] },
      { emoji: '⚔️', keywords: ['swords', 'crossed'] },
      { emoji: '🛡️', keywords: ['shield', 'security'] },
      { emoji: '🔧', keywords: ['wrench', 'spanner', 'tool'] },
      { emoji: '🪛', keywords: ['screwdriver', 'tool'] },
      { emoji: '🔩', keywords: ['nut', 'bolt'] },
      { emoji: '⚙️', keywords: ['gear', 'cog', 'settings'] },
      { emoji: '⚖️', keywords: ['scales', 'balance', 'justice'] },
      { emoji: '🔗', keywords: ['link', 'chain'] },
      { emoji: '⛓️', keywords: ['chains'] },
      { emoji: '🪝', keywords: ['hook'] },
      { emoji: '🧰', keywords: ['toolbox', 'tools'] },
      { emoji: '🧲', keywords: ['magnet'] },
      { emoji: '🪜', keywords: ['ladder'] },
      { emoji: '🧪', keywords: ['test', 'tube', 'science'] },
      { emoji: '🧫', keywords: ['petri', 'dish', 'science'] },
      { emoji: '🧬', keywords: ['dna', 'gene', 'science'] },
      { emoji: '🔬', keywords: ['microscope', 'science'] },
      { emoji: '🔭', keywords: ['telescope', 'astronomy'] },
      { emoji: '📡', keywords: ['satellite', 'antenna', 'dish'] },
    ],
  },
};
