import type { EmojiData } from '../types';

export const PEOPLE_EMOJI_DATA: EmojiData = {
  'Smileys & People': {
    emojis: [
      { emoji: '😀', keywords: ['grinning', 'face', 'smile', 'happy'] },
      { emoji: '😃', keywords: ['smiley', 'face', 'happy', 'joy'] },
      { emoji: '😄', keywords: ['smile', 'face', 'happy', 'joy'] },
      { emoji: '😁', keywords: ['grin', 'face', 'happy'] },
      { emoji: '😆', keywords: ['laughing', 'satisfied', 'face'] },
      { emoji: '😅', keywords: ['sweat', 'smile', 'nervous'] },
      { emoji: '🤣', keywords: ['rofl', 'laughing', 'floor'] },
      { emoji: '😂', keywords: ['joy', 'tears', 'laughing', 'funny'] },
      { emoji: '🙂', keywords: ['slightly', 'smiling', 'face'] },
      { emoji: '🙃', keywords: ['upside', 'down', 'face'] },
      { emoji: '😉', keywords: ['wink', 'face'] },
      { emoji: '😊', keywords: ['blush', 'smile', 'happy'] },
      { emoji: '😇', keywords: ['innocent', 'angel', 'halo'] },
      { emoji: '🥰', keywords: ['love', 'hearts', 'smiling'] },
      { emoji: '😍', keywords: ['heart', 'eyes', 'love'] },
      { emoji: '🤩', keywords: ['star', 'struck', 'excited'] },
      { emoji: '😘', keywords: ['kiss', 'face', 'love'] },
      { emoji: '😗', keywords: ['kissing', 'face'] },
      { emoji: '😚', keywords: ['kissing', 'closed', 'eyes'] },
      { emoji: '😙', keywords: ['kissing', 'smiling'] },
      { emoji: '🥲', keywords: ['smiling', 'tear', 'grateful'] },
      { emoji: '😋', keywords: ['yum', 'delicious', 'tongue'] },
      { emoji: '😛', keywords: ['tongue', 'out', 'playful'] },
      { emoji: '😜', keywords: ['wink', 'tongue', 'crazy'] },
      { emoji: '🤪', keywords: ['zany', 'crazy', 'goofy'] },
      { emoji: '😝', keywords: ['tongue', 'closed', 'eyes'] },
      { emoji: '🤑', keywords: ['money', 'rich', 'dollar'] },
      { emoji: '🤗', keywords: ['hugging', 'hug', 'face'] },
      { emoji: '🤭', keywords: ['giggle', 'covering', 'mouth'] },
      { emoji: '🤫', keywords: ['shush', 'quiet', 'secret'] },
      { emoji: '🤔', keywords: ['thinking', 'face', 'hmm'] },
      { emoji: '🤐', keywords: ['zipper', 'mouth', 'quiet'] },
      { emoji: '🤨', keywords: ['raised', 'eyebrow', 'skeptical'] },
      { emoji: '😐', keywords: ['neutral', 'face', 'meh'] },
      { emoji: '😑', keywords: ['expressionless', 'face'] },
      { emoji: '😶', keywords: ['no', 'mouth', 'silent'] },
      { emoji: '😏', keywords: ['smirk', 'face', 'smug'] },
      { emoji: '😒', keywords: ['unamused', 'face', 'meh'] },
      { emoji: '🙄', keywords: ['eye', 'roll', 'annoyed'] },
      { emoji: '😬', keywords: ['grimace', 'awkward'] },
      { emoji: '🤥', keywords: ['lying', 'pinocchio', 'nose'] },
      { emoji: '😌', keywords: ['relieved', 'peaceful'] },
      { emoji: '😔', keywords: ['pensive', 'sad', 'thoughtful'] },
      { emoji: '😪', keywords: ['sleepy', 'tired'] },
      { emoji: '🤤', keywords: ['drooling', 'hungry'] },
      { emoji: '😴', keywords: ['sleeping', 'zzz', 'tired'] },
      { emoji: '😷', keywords: ['mask', 'sick', 'medical'] },
      { emoji: '🤒', keywords: ['thermometer', 'sick', 'fever'] },
      { emoji: '🤕', keywords: ['bandage', 'hurt', 'injured'] },
      { emoji: '🤢', keywords: ['nauseated', 'sick', 'green'] },
      { emoji: '🤮', keywords: ['vomiting', 'sick', 'throw up'] },
      { emoji: '🤧', keywords: ['sneezing', 'sick', 'tissue'] },
      { emoji: '🥵', keywords: ['hot', 'sweating', 'heat'] },
      { emoji: '🥶', keywords: ['cold', 'freezing', 'frozen'] },
      { emoji: '🥴', keywords: ['woozy', 'dizzy', 'drunk'] },
      { emoji: '😵', keywords: ['dizzy', 'knocked', 'out'] },
      { emoji: '🤯', keywords: ['exploding', 'head', 'mind blown'] },
      { emoji: '🤠', keywords: ['cowboy', 'hat', 'western'] },
      { emoji: '🥳', keywords: ['party', 'celebration', 'birthday'] },
      { emoji: '🥸', keywords: ['disguise', 'glasses', 'nose'] },
      { emoji: '😎', keywords: ['cool', 'sunglasses', 'awesome'] },
      { emoji: '🤓', keywords: ['nerd', 'glasses', 'geek'] },
      { emoji: '🧐', keywords: ['monocle', 'thinking', 'curious'] },
      { emoji: '😕', keywords: ['confused', 'face'] },
      { emoji: '😟', keywords: ['worried', 'concerned'] },
      { emoji: '🙁', keywords: ['slightly', 'frowning'] },
      { emoji: '☹️', keywords: ['frowning', 'sad'] },
      { emoji: '😮', keywords: ['open', 'mouth', 'surprised'] },
      { emoji: '😯', keywords: ['hushed', 'surprised'] },
      { emoji: '😲', keywords: ['astonished', 'shocked'] },
      { emoji: '😳', keywords: ['flushed', 'embarrassed'] },
      { emoji: '🥺', keywords: ['pleading', 'puppy', 'eyes'] },
      { emoji: '😦', keywords: ['frowning', 'open', 'mouth'] },
      { emoji: '😧', keywords: ['anguished', 'face'] },
      { emoji: '😨', keywords: ['fearful', 'scared'] },
      { emoji: '😰', keywords: ['anxious', 'sweat'] },
      { emoji: '😥', keywords: ['sad', 'relieved'] },
      { emoji: '😢', keywords: ['crying', 'tear', 'sad'] },
      { emoji: '😭', keywords: ['sobbing', 'crying', 'tears'] },
      { emoji: '😱', keywords: ['screaming', 'fear', 'horror'] },
      { emoji: '😖', keywords: ['confounded', 'frustrated'] },
      { emoji: '😣', keywords: ['persevering', 'struggling'] },
      { emoji: '😞', keywords: ['disappointed', 'sad'] },
      { emoji: '😓', keywords: ['downcast', 'sweat'] },
      { emoji: '😩', keywords: ['weary', 'tired'] },
      { emoji: '😫', keywords: ['tired', 'exhausted'] },
      { emoji: '🥱', keywords: ['yawning', 'tired', 'bored'] },
      { emoji: '😤', keywords: ['triumph', 'huffing', 'angry'] },
      { emoji: '😡', keywords: ['angry', 'pouting', 'mad'] },
      { emoji: '😠', keywords: ['angry', 'face', 'mad'] },
      { emoji: '🤬', keywords: ['cursing', 'swearing', 'angry'] },
      { emoji: '😈', keywords: ['devil', 'smiling', 'horns'] },
      { emoji: '👿', keywords: ['devil', 'angry', 'imp'] },
      { emoji: '💀', keywords: ['skull', 'death', 'dead'] },
      { emoji: '☠️', keywords: ['skull', 'crossbones', 'danger'] },
      { emoji: '💩', keywords: ['poop', 'poo'] },
      { emoji: '🤡', keywords: ['clown', 'face'] },
      { emoji: '👹', keywords: ['ogre', 'monster', 'japanese'] },
      { emoji: '👺', keywords: ['goblin', 'tengu', 'japanese'] },
      { emoji: '👻', keywords: ['ghost', 'halloween', 'boo'] },
      { emoji: '👽', keywords: ['alien', 'ufo', 'extraterrestrial'] },
      { emoji: '👾', keywords: ['alien', 'monster', 'game'] },
      { emoji: '🤖', keywords: ['robot', 'face', 'bot'] },
      { emoji: '😺', keywords: ['cat', 'smile', 'happy'] },
      { emoji: '😸', keywords: ['cat', 'grin'] },
      { emoji: '😹', keywords: ['cat', 'joy', 'tears'] },
      { emoji: '😻', keywords: ['cat', 'heart', 'eyes', 'love'] },
      { emoji: '😼', keywords: ['cat', 'smirk'] },
      { emoji: '😽', keywords: ['cat', 'kiss'] },
      { emoji: '🙀', keywords: ['cat', 'weary', 'surprised'] },
      { emoji: '😿', keywords: ['cat', 'crying', 'sad'] },
      { emoji: '😾', keywords: ['cat', 'pouting', 'angry'] },
      { emoji: '🙈', keywords: ['monkey', 'see', 'no', 'evil'] },
      { emoji: '🙉', keywords: ['monkey', 'hear', 'no', 'evil'] },
      { emoji: '🙊', keywords: ['monkey', 'speak', 'no', 'evil'] },
    ],
  },
  'Gestures & Body': {
    emojis: [
      { emoji: '👋', keywords: ['wave', 'hand', 'hello', 'bye'] },
      { emoji: '🤚', keywords: ['raised', 'back', 'hand'] },
      { emoji: '🖐️', keywords: ['hand', 'fingers', 'splayed'] },
      { emoji: '✋', keywords: ['raised', 'hand', 'stop'] },
      { emoji: '🖖', keywords: ['vulcan', 'salute', 'spock'] },
      { emoji: '👌', keywords: ['ok', 'hand', 'perfect'] },
      { emoji: '🤌', keywords: ['pinched', 'fingers', 'italian'] },
      { emoji: '🤏', keywords: ['pinching', 'hand', 'small'] },
      { emoji: '✌️', keywords: ['victory', 'peace', 'hand'] },
      { emoji: '🤞', keywords: ['crossed', 'fingers', 'luck'] },
      { emoji: '🤟', keywords: ['love', 'you', 'gesture'] },
      { emoji: '🤘', keywords: ['rock', 'on', 'horns'] },
      { emoji: '🤙', keywords: ['call', 'me', 'hand', 'shaka'] },
      { emoji: '👈', keywords: ['pointing', 'left'] },
      { emoji: '👉', keywords: ['pointing', 'right'] },
      { emoji: '👆', keywords: ['pointing', 'up'] },
      { emoji: '🖕', keywords: ['middle', 'finger'] },
      { emoji: '👇', keywords: ['pointing', 'down'] },
      { emoji: '☝️', keywords: ['index', 'pointing', 'up'] },
      { emoji: '👍', keywords: ['thumbs', 'up', 'like', 'good'] },
      { emoji: '👎', keywords: ['thumbs', 'down', 'dislike', 'bad'] },
      { emoji: '✊', keywords: ['fist', 'raised', 'power'] },
      { emoji: '👊', keywords: ['fist', 'bump', 'punch'] },
      { emoji: '🤛', keywords: ['fist', 'left'] },
      { emoji: '🤜', keywords: ['fist', 'right'] },
      { emoji: '👏', keywords: ['clap', 'hands', 'applause'] },
      { emoji: '🙌', keywords: ['raised', 'hands', 'celebration'] },
      { emoji: '👐', keywords: ['open', 'hands'] },
      { emoji: '🤲', keywords: ['palms', 'up', 'together'] },
      { emoji: '🤝', keywords: ['handshake', 'deal', 'agreement'] },
      { emoji: '🙏', keywords: ['pray', 'hands', 'please', 'thank'] },
      { emoji: '✍️', keywords: ['writing', 'hand'] },
      { emoji: '💅', keywords: ['nail', 'polish', 'beauty'] },
      { emoji: '🤳', keywords: ['selfie'] },
      { emoji: '💪', keywords: ['muscle', 'bicep', 'strong', 'flex'] },
      { emoji: '🦾', keywords: ['mechanical', 'arm', 'prosthetic'] },
      { emoji: '🦿', keywords: ['mechanical', 'leg', 'prosthetic'] },
      { emoji: '🦵', keywords: ['leg'] },
      { emoji: '🦶', keywords: ['foot'] },
      { emoji: '👂', keywords: ['ear', 'listen', 'hear'] },
      { emoji: '🦻', keywords: ['ear', 'hearing', 'aid'] },
      { emoji: '👃', keywords: ['nose', 'smell'] },
      { emoji: '🧠', keywords: ['brain', 'think', 'mind'] },
      { emoji: '🫀', keywords: ['heart', 'anatomical', 'organ'] },
      { emoji: '🫁', keywords: ['lungs', 'breathe', 'organ'] },
      { emoji: '🦷', keywords: ['tooth', 'dental'] },
      { emoji: '🦴', keywords: ['bone', 'skeleton'] },
      { emoji: '👀', keywords: ['eyes', 'look', 'see'] },
      { emoji: '👁️', keywords: ['eye', 'look'] },
      { emoji: '👅', keywords: ['tongue', 'taste'] },
      { emoji: '👄', keywords: ['mouth', 'lips', 'kiss'] },
    ],
  },
};
