import type { EmojiData } from '../types';

export const SYMBOLS_EMOJI_DATA: EmojiData = {
  Symbols: {
    emojis: [
      { emoji: '❤️', keywords: ['heart', 'red', 'love'] },
      { emoji: '🧡', keywords: ['heart', 'orange', 'love'] },
      { emoji: '💛', keywords: ['heart', 'yellow', 'love'] },
      { emoji: '💚', keywords: ['heart', 'green', 'love'] },
      { emoji: '💙', keywords: ['heart', 'blue', 'love'] },
      { emoji: '💜', keywords: ['heart', 'purple', 'love'] },
      { emoji: '🖤', keywords: ['heart', 'black', 'love'] },
      { emoji: '🤍', keywords: ['heart', 'white', 'love'] },
      { emoji: '🤎', keywords: ['heart', 'brown', 'love'] },
      { emoji: '💔', keywords: ['heart', 'broken', 'sad'] },
      { emoji: '❣️', keywords: ['heart', 'exclamation'] },
      { emoji: '💕', keywords: ['hearts', 'two', 'love'] },
      { emoji: '💞', keywords: ['hearts', 'revolving', 'love'] },
      { emoji: '💓', keywords: ['heart', 'beating', 'love'] },
      { emoji: '💗', keywords: ['heart', 'growing', 'love'] },
      { emoji: '💖', keywords: ['heart', 'sparkling', 'love'] },
      { emoji: '💘', keywords: ['heart', 'arrow', 'cupid', 'love'] },
      { emoji: '💝', keywords: ['heart', 'ribbon', 'gift', 'love'] },
      { emoji: '💟', keywords: ['heart', 'decoration'] },
      { emoji: '☮️', keywords: ['peace', 'symbol'] },
      { emoji: '✝️', keywords: ['cross', 'christian', 'latin'] },
      { emoji: '☪️', keywords: ['star', 'crescent', 'islam'] },
      { emoji: '🕉️', keywords: ['om', 'hindu'] },
      { emoji: '☸️', keywords: ['wheel', 'dharma', 'buddhist'] },
      { emoji: '✡️', keywords: ['star', 'david', 'jewish'] },
      { emoji: '🔯', keywords: ['star', 'six', 'pointed'] },
      { emoji: '🕎', keywords: ['menorah', 'jewish'] },
      { emoji: '☯️', keywords: ['yin', 'yang', 'balance'] },
      { emoji: '☦️', keywords: ['cross', 'orthodox'] },
      { emoji: '🆔', keywords: ['id', 'identity'] },
      { emoji: '⚛️', keywords: ['atom', 'science'] },
      { emoji: '☢️', keywords: ['radioactive'] },
      { emoji: '☣️', keywords: ['biohazard'] },
      { emoji: '🆚', keywords: ['versus', 'vs'] },
      { emoji: '🅰️', keywords: ['a', 'blood', 'type'] },
      { emoji: '🅱️', keywords: ['b', 'blood', 'type'] },
      { emoji: '🆎', keywords: ['ab', 'blood', 'type'] },
      { emoji: '🆑', keywords: ['cl', 'clear'] },
      { emoji: '🅾️', keywords: ['o', 'blood', 'type'] },
      { emoji: '🆘', keywords: ['sos', 'help', 'emergency'] },
      { emoji: '❌', keywords: ['x', 'cross', 'mark', 'no'] },
      { emoji: '⭕', keywords: ['circle', 'o', 'ring'] },
      { emoji: '🛑', keywords: ['stop', 'sign', 'octagonal'] },
      { emoji: '⛔', keywords: ['no', 'entry', 'prohibited'] },
      { emoji: '📛', keywords: ['name', 'badge'] },
      { emoji: '🚫', keywords: ['prohibited', 'forbidden', 'no'] },
      { emoji: '💯', keywords: ['hundred', 'points', 'score', 'perfect'] },
      { emoji: '💢', keywords: ['anger', 'symbol', 'angry'] },
      { emoji: '♨️', keywords: ['hot', 'springs'] },
      { emoji: '🔞', keywords: ['no', 'one', 'under', 'eighteen', '18'] },
      { emoji: '❗', keywords: ['exclamation', 'mark', 'red'] },
      { emoji: '❓', keywords: ['question', 'mark', 'red'] },
      { emoji: '‼️', keywords: ['exclamation', 'double'] },
      { emoji: '⁉️', keywords: ['exclamation', 'question'] },
      { emoji: '💬', keywords: ['speech', 'balloon', 'comment'] },
      { emoji: '💭', keywords: ['thought', 'balloon'] },
      { emoji: '💤', keywords: ['zzz', 'sleep'] },
      { emoji: '🔰', keywords: ['beginner', 'japanese'] },
      { emoji: '🔱', keywords: ['trident', 'emblem'] },
      { emoji: '✅', keywords: ['check', 'mark', 'button', 'yes'] },
      { emoji: '☑️', keywords: ['check', 'box'] },
      { emoji: '✔️', keywords: ['check', 'mark'] },
      { emoji: '➕', keywords: ['plus', 'add'] },
      { emoji: '➖', keywords: ['minus', 'subtract'] },
      { emoji: '➗', keywords: ['divide', 'division'] },
      { emoji: '✖️', keywords: ['multiply', 'x'] },
      { emoji: '♾️', keywords: ['infinity'] },
      { emoji: '💲', keywords: ['dollar', 'sign', 'money'] },
      { emoji: '💱', keywords: ['currency', 'exchange'] },
      { emoji: '™️', keywords: ['trademark'] },
      { emoji: '©️', keywords: ['copyright'] },
      { emoji: '®️', keywords: ['registered'] },
      { emoji: '〰️', keywords: ['wavy', 'dash'] },
      { emoji: '➰', keywords: ['curly', 'loop'] },
      { emoji: '➿', keywords: ['double', 'curly', 'loop'] },
      { emoji: '🔚', keywords: ['end', 'arrow'] },
      { emoji: '🔙', keywords: ['back', 'arrow'] },
      { emoji: '🔛', keywords: ['on', 'arrow'] },
      { emoji: '🔝', keywords: ['top', 'arrow'] },
      { emoji: '🔜', keywords: ['soon', 'arrow'] },
      { emoji: '⬆️', keywords: ['up', 'arrow'] },
      { emoji: '⬇️', keywords: ['down', 'arrow'] },
      { emoji: '⬅️', keywords: ['left', 'arrow'] },
      { emoji: '➡️', keywords: ['right', 'arrow'] },
      { emoji: '↗️', keywords: ['up', 'right', 'arrow'] },
      { emoji: '↘️', keywords: ['down', 'right', 'arrow'] },
      { emoji: '↙️', keywords: ['down', 'left', 'arrow'] },
      { emoji: '↖️', keywords: ['up', 'left', 'arrow'] },
      { emoji: '↕️', keywords: ['up', 'down', 'arrow'] },
      { emoji: '↔️', keywords: ['left', 'right', 'arrow'] },
      { emoji: '↩️', keywords: ['right', 'curving', 'left', 'arrow'] },
      { emoji: '↪️', keywords: ['left', 'curving', 'right', 'arrow'] },
      { emoji: '⤴️', keywords: ['right', 'curving', 'up', 'arrow'] },
      { emoji: '⤵️', keywords: ['right', 'curving', 'down', 'arrow'] },
      { emoji: '🔀', keywords: ['shuffle', 'tracks'] },
      { emoji: '🔁', keywords: ['repeat'] },
      { emoji: '🔂', keywords: ['repeat', 'single'] },
      { emoji: '🔃', keywords: ['clockwise', 'arrows'] },
      { emoji: '🔄', keywords: ['counterclockwise', 'arrows'] },
      { emoji: '🎵', keywords: ['musical', 'note', 'music'] },
      { emoji: '🎶', keywords: ['musical', 'notes', 'music'] },
      { emoji: '🔅', keywords: ['dim', 'button', 'low', 'brightness'] },
      { emoji: '🔆', keywords: ['bright', 'button', 'high', 'brightness'] },
      { emoji: '♀️', keywords: ['female', 'sign', 'woman'] },
      { emoji: '♂️', keywords: ['male', 'sign', 'man'] },
      { emoji: '⚕️', keywords: ['medical', 'symbol'] },
      { emoji: '♻️', keywords: ['recycling', 'recycle', 'symbol'] },
      { emoji: '⚜️', keywords: ['fleur-de-lis'] },
      { emoji: '⭐', keywords: ['star', 'yellow'] },
      { emoji: '🌟', keywords: ['glowing', 'star', 'sparkle'] },
      { emoji: '✨', keywords: ['sparkles', 'stars', 'shine'] },
      { emoji: '💫', keywords: ['dizzy', 'star'] },
      { emoji: '🌠', keywords: ['shooting', 'star'] },
    ],
  },
  'Weather & Sky': {
    emojis: [
      { emoji: '☀️', keywords: ['sun', 'sunny', 'weather'] },
      { emoji: '🌤️', keywords: ['sun', 'small', 'cloud'] },
      { emoji: '⛅', keywords: ['sun', 'behind', 'cloud'] },
      { emoji: '🌥️', keywords: ['sun', 'behind', 'large', 'cloud'] },
      { emoji: '☁️', keywords: ['cloud', 'weather'] },
      { emoji: '🌦️', keywords: ['sun', 'behind', 'rain', 'cloud'] },
      { emoji: '🌧️', keywords: ['cloud', 'rain', 'weather'] },
      { emoji: '⛈️', keywords: ['cloud', 'lightning', 'rain', 'thunder'] },
      { emoji: '🌩️', keywords: ['cloud', 'lightning'] },
      { emoji: '🌨️', keywords: ['cloud', 'snow', 'weather'] },
      { emoji: '❄️', keywords: ['snowflake', 'cold', 'winter'] },
      { emoji: '☃️', keywords: ['snowman', 'snow', 'winter'] },
      { emoji: '⛄', keywords: ['snowman', 'no', 'snow'] },
      { emoji: '🌬️', keywords: ['wind', 'face', 'blow'] },
      { emoji: '💨', keywords: ['dash', 'wind', 'fast'] },
      { emoji: '🌪️', keywords: ['tornado', 'weather'] },
      { emoji: '🌫️', keywords: ['fog', 'weather'] },
      { emoji: '🌈', keywords: ['rainbow'] },
      { emoji: '🌙', keywords: ['crescent', 'moon', 'night'] },
      { emoji: '🌛', keywords: ['first', 'quarter', 'moon', 'face'] },
      { emoji: '🌜', keywords: ['last', 'quarter', 'moon', 'face'] },
      { emoji: '🌝', keywords: ['full', 'moon', 'face'] },
      { emoji: '🌞', keywords: ['sun', 'face'] },
      { emoji: '☄️', keywords: ['comet', 'space'] },
      { emoji: '🔥', keywords: ['fire', 'flame', 'hot'] },
      { emoji: '💧', keywords: ['droplet', 'water', 'sweat'] },
      { emoji: '🌊', keywords: ['wave', 'water', 'ocean', 'sea'] },
      { emoji: '💥', keywords: ['collision', 'boom', 'explosion'] },
    ],
  },
  Flags: {
    emojis: [
      { emoji: '🏁', keywords: ['checkered', 'flag', 'race', 'finish'] },
      { emoji: '🚩', keywords: ['triangular', 'flag', 'red'] },
      { emoji: '🎌', keywords: ['crossed', 'flags', 'japanese'] },
      { emoji: '🏴', keywords: ['black', 'flag'] },
      { emoji: '🏳️', keywords: ['white', 'flag', 'surrender'] },
      { emoji: '🏳️‍🌈', keywords: ['rainbow', 'flag', 'pride', 'lgbt'] },
      { emoji: '🏳️‍⚧️', keywords: ['transgender', 'flag', 'pride'] },
      { emoji: '🏴‍☠️', keywords: ['pirate', 'flag', 'jolly', 'roger'] },
      { emoji: '🇻🇳', keywords: ['vietnam', 'flag', 'vietnamese'] },
      { emoji: '🇺🇸', keywords: ['us', 'usa', 'america', 'united', 'states', 'flag'] },
      { emoji: '🇬🇧', keywords: ['uk', 'united', 'kingdom', 'britain', 'flag'] },
      { emoji: '🇫🇷', keywords: ['france', 'french', 'flag'] },
      { emoji: '🇩🇪', keywords: ['germany', 'german', 'flag'] },
      { emoji: '🇯🇵', keywords: ['japan', 'japanese', 'flag'] },
      { emoji: '🇰🇷', keywords: ['korea', 'korean', 'south', 'flag'] },
      { emoji: '🇨🇳', keywords: ['china', 'chinese', 'flag'] },
      { emoji: '🇮🇳', keywords: ['india', 'indian', 'flag'] },
      { emoji: '🇧🇷', keywords: ['brazil', 'brazilian', 'flag'] },
      { emoji: '🇲🇽', keywords: ['mexico', 'mexican', 'flag'] },
      { emoji: '🇨🇦', keywords: ['canada', 'canadian', 'flag'] },
      { emoji: '🇦🇺', keywords: ['australia', 'australian', 'flag'] },
      { emoji: '🇮🇹', keywords: ['italy', 'italian', 'flag'] },
      { emoji: '🇪🇸', keywords: ['spain', 'spanish', 'flag'] },
      { emoji: '🇷🇺', keywords: ['russia', 'russian', 'flag'] },
      { emoji: '🇹🇭', keywords: ['thailand', 'thai', 'flag'] },
      { emoji: '🇵🇭', keywords: ['philippines', 'filipino', 'flag'] },
      { emoji: '🇮🇩', keywords: ['indonesia', 'indonesian', 'flag'] },
      { emoji: '🇲🇾', keywords: ['malaysia', 'malaysian', 'flag'] },
      { emoji: '🇸🇬', keywords: ['singapore', 'singaporean', 'flag'] },
    ],
  },
};
