import type { LucideIconItem } from './types';

export const LUCIDE_ICON_DATA: LucideIconItem[] = [
  // Hearts & Love
  { name: 'heart', keywords: ['love', 'like', 'favorite', 'romance', 'valentine'] },
  { name: 'heart-pulse', keywords: ['love', 'health', 'heartbeat', 'alive', 'medical'] },
  { name: 'heart-crack', keywords: ['love', 'broken', 'sad', 'heartbreak'] },
  { name: 'heart-off', keywords: ['love', 'unlike', 'disable'] },
  { name: 'heart-handshake', keywords: ['love', 'care', 'support', 'partnership'] },

  // Fire & Energy
  { name: 'flame', keywords: ['fire', 'hot', 'burn', 'trending', 'popular'] },
  { name: 'zap', keywords: ['lightning', 'electric', 'power', 'energy', 'fast', 'bolt'] },
  { name: 'zap-off', keywords: ['lightning', 'electric', 'power', 'off'] },
  { name: 'sparkle', keywords: ['magic', 'new', 'special', 'shine', 'star'] },
  { name: 'sparkles', keywords: ['magic', 'new', 'special', 'shine', 'stars', 'ai'] },

  // Stars & Celestial
  { name: 'star', keywords: ['favorite', 'rating', 'bookmark', 'night', 'space'] },
  { name: 'sun', keywords: ['day', 'light', 'bright', 'weather', 'morning'] },
  { name: 'moon', keywords: ['night', 'dark', 'sleep', 'space'] },
  { name: 'cloud', keywords: ['weather', 'sky', 'storage', 'upload'] },
  { name: 'cloud-rain', keywords: ['weather', 'rainy', 'storm'] },
  { name: 'cloud-snow', keywords: ['weather', 'winter', 'cold', 'snowy'] },
  { name: 'cloud-lightning', keywords: ['weather', 'storm', 'thunder'] },
  { name: 'cloud-sun', keywords: ['weather', 'partly', 'cloudy'] },
  { name: 'rainbow', keywords: ['weather', 'colorful', 'pride', 'happy'] },
  { name: 'snowflake', keywords: ['winter', 'cold', 'frozen', 'ice'] },

  // Nature & Plants
  { name: 'leaf', keywords: ['nature', 'plant', 'eco', 'green', 'organic'] },
  { name: 'tree-pine', keywords: ['nature', 'forest', 'christmas', 'evergreen'] },
  { name: 'trees', keywords: ['nature', 'forest', 'woods', 'park'] },
  { name: 'flower', keywords: ['nature', 'plant', 'garden', 'bloom', 'spring'] },
  { name: 'flower-2', keywords: ['nature', 'plant', 'garden', 'bloom'] },
  { name: 'sprout', keywords: ['nature', 'grow', 'seed', 'plant', 'new'] },
  { name: 'mountain', keywords: ['nature', 'hiking', 'outdoor', 'peak'] },
  { name: 'mountain-snow', keywords: ['nature', 'winter', 'skiing', 'alps'] },
  { name: 'waves', keywords: ['water', 'ocean', 'sea', 'beach'] },
  { name: 'droplet', keywords: ['water', 'rain', 'liquid', 'tear'] },
  { name: 'droplets', keywords: ['water', 'rain', 'wet', 'humidity'] },
  { name: 'wind', keywords: ['weather', 'air', 'blow', 'breeze'] },
  { name: 'umbrella', keywords: ['rain', 'weather', 'protection'] },

  // Food & Drinks
  { name: 'apple', keywords: ['fruit', 'food', 'healthy', 'teacher'] },
  { name: 'banana', keywords: ['fruit', 'food', 'yellow'] },
  { name: 'cherry', keywords: ['fruit', 'food', 'red'] },
  { name: 'citrus', keywords: ['fruit', 'food', 'orange', 'lemon'] },
  { name: 'grape', keywords: ['fruit', 'food', 'wine', 'purple'] },
  { name: 'carrot', keywords: ['vegetable', 'food', 'orange', 'healthy'] },
  { name: 'salad', keywords: ['food', 'healthy', 'vegetable', 'diet'] },
  { name: 'pizza', keywords: ['food', 'italian', 'fast food', 'slice'] },
  { name: 'sandwich', keywords: ['food', 'lunch', 'bread'] },
  { name: 'cookie', keywords: ['food', 'dessert', 'sweet', 'snack'] },
  { name: 'cake', keywords: ['food', 'dessert', 'birthday', 'sweet', 'celebration'] },
  { name: 'ice-cream-cone', keywords: ['food', 'dessert', 'sweet', 'cold', 'summer'] },
  { name: 'coffee', keywords: ['drink', 'caffeine', 'morning', 'cafe', 'hot'] },
  { name: 'cup-soda', keywords: ['drink', 'soda', 'beverage', 'cold'] },
  { name: 'beer', keywords: ['drink', 'alcohol', 'bar', 'pub'] },
  { name: 'wine', keywords: ['drink', 'alcohol', 'grape', 'dinner'] },
  { name: 'martini', keywords: ['drink', 'alcohol', 'cocktail', 'bar'] },
  { name: 'milk', keywords: ['drink', 'dairy', 'calcium'] },
  { name: 'egg', keywords: ['food', 'breakfast', 'protein'] },
  { name: 'egg-fried', keywords: ['food', 'breakfast', 'cooking'] },
  { name: 'beef', keywords: ['food', 'meat', 'steak', 'protein'] },
  { name: 'fish', keywords: ['food', 'seafood', 'animal', 'ocean'] },
  { name: 'drumstick', keywords: ['food', 'chicken', 'meat'] },
  { name: 'popcorn', keywords: ['food', 'snack', 'movie', 'cinema'] },
  { name: 'candy', keywords: ['food', 'sweet', 'sugar', 'treat'] },
  { name: 'lollipop', keywords: ['food', 'sweet', 'candy', 'sugar'] },
  { name: 'croissant', keywords: ['food', 'bread', 'breakfast', 'french', 'pastry'] },
  { name: 'soup', keywords: ['food', 'hot', 'bowl', 'meal'] },
  { name: 'utensils', keywords: ['food', 'eat', 'restaurant', 'dining', 'fork', 'knife'] },
  { name: 'chef-hat', keywords: ['food', 'cook', 'kitchen', 'restaurant'] },

  // Animals
  { name: 'cat', keywords: ['animal', 'pet', 'meow', 'kitty', 'feline'] },
  { name: 'dog', keywords: ['animal', 'pet', 'bark', 'puppy', 'canine'] },
  { name: 'bird', keywords: ['animal', 'fly', 'tweet', 'nature'] },
  { name: 'bug', keywords: ['animal', 'insect', 'code', 'error'] },
  { name: 'rabbit', keywords: ['animal', 'bunny', 'pet', 'easter'] },
  { name: 'turtle', keywords: ['animal', 'slow', 'shell', 'reptile'] },
  { name: 'shell', keywords: ['animal', 'beach', 'ocean', 'sea'] },
  { name: 'paw-print', keywords: ['animal', 'pet', 'dog', 'cat', 'track'] },
  { name: 'feather', keywords: ['animal', 'bird', 'light', 'write'] },
  { name: 'squirrel', keywords: ['animal', 'nature', 'nut', 'forest'] },
  { name: 'rat', keywords: ['animal', 'rodent', 'mouse'] },

  // People & Body
  { name: 'user', keywords: ['person', 'account', 'profile', 'member'] },
  { name: 'user-plus', keywords: ['person', 'add', 'new', 'invite'] },
  { name: 'user-minus', keywords: ['person', 'remove', 'delete'] },
  { name: 'user-x', keywords: ['person', 'remove', 'delete', 'block'] },
  { name: 'user-check', keywords: ['person', 'verify', 'approved'] },
  { name: 'user-cog', keywords: ['person', 'settings', 'admin'] },
  { name: 'user-circle', keywords: ['person', 'avatar', 'profile'] },
  { name: 'users', keywords: ['people', 'group', 'team', 'community'] },
  { name: 'contact', keywords: ['person', 'address', 'book'] },
  { name: 'baby', keywords: ['person', 'child', 'infant', 'kid'] },
  { name: 'accessibility', keywords: ['person', 'disabled', 'wheelchair'] },
  { name: 'smile', keywords: ['face', 'happy', 'emoji', 'emotion'] },
  { name: 'frown', keywords: ['face', 'sad', 'emoji', 'emotion'] },
  { name: 'meh', keywords: ['face', 'neutral', 'emoji', 'emotion'] },
  { name: 'laugh', keywords: ['face', 'happy', 'funny', 'lol'] },
  { name: 'angry', keywords: ['face', 'mad', 'emoji', 'emotion'] },
  { name: 'thumbs-up', keywords: ['like', 'approve', 'good', 'yes', 'hand'] },
  { name: 'thumbs-down', keywords: ['dislike', 'disapprove', 'bad', 'no', 'hand'] },
  { name: 'hand', keywords: ['stop', 'wave', 'high five'] },
  { name: 'handshake', keywords: ['deal', 'agreement', 'partnership', 'meeting'] },

  // Home & Buildings
  { name: 'home', keywords: ['house', 'main', 'start', 'residence'] },
  { name: 'house', keywords: ['home', 'building', 'residence'] },
  { name: 'building', keywords: ['office', 'work', 'company', 'city'] },
  { name: 'building-2', keywords: ['office', 'work', 'company', 'city'] },
  { name: 'store', keywords: ['shop', 'retail', 'buy', 'market'] },
  { name: 'warehouse', keywords: ['storage', 'inventory', 'factory'] },
  { name: 'factory', keywords: ['industry', 'manufacturing', 'production'] },
  { name: 'hospital', keywords: ['medical', 'health', 'doctor', 'emergency'] },
  { name: 'hotel', keywords: ['travel', 'stay', 'vacation', 'room'] },
  { name: 'school', keywords: ['education', 'learn', 'student', 'study'] },
  { name: 'church', keywords: ['religion', 'faith', 'worship', 'building'] },
  { name: 'landmark', keywords: ['place', 'monument', 'famous', 'destination'] },
  { name: 'castle', keywords: ['building', 'medieval', 'kingdom', 'fortress'] },
  { name: 'tent', keywords: ['camping', 'outdoor', 'nature', 'travel'] },
  { name: 'construction', keywords: ['building', 'work', 'site'] },

  // Transport
  { name: 'car', keywords: ['vehicle', 'drive', 'auto', 'transport'] },
  { name: 'car-front', keywords: ['vehicle', 'drive', 'auto', 'transport'] },
  { name: 'truck', keywords: ['vehicle', 'delivery', 'transport', 'shipping'] },
  { name: 'bus', keywords: ['vehicle', 'public', 'transport', 'travel'] },
  { name: 'train', keywords: ['vehicle', 'rail', 'transport', 'travel'] },
  { name: 'train-front', keywords: ['vehicle', 'rail', 'metro', 'subway'] },
  { name: 'plane', keywords: ['vehicle', 'fly', 'travel', 'airport', 'flight'] },
  { name: 'plane-takeoff', keywords: ['vehicle', 'fly', 'departure', 'airport'] },
  { name: 'plane-landing', keywords: ['vehicle', 'fly', 'arrival', 'airport'] },
  { name: 'ship', keywords: ['vehicle', 'boat', 'ocean', 'cruise', 'sea'] },
  { name: 'sailboat', keywords: ['vehicle', 'boat', 'sail', 'ocean', 'yacht'] },
  { name: 'anchor', keywords: ['ship', 'boat', 'marine', 'port'] },
  { name: 'rocket', keywords: ['space', 'launch', 'fast', 'startup'] },
  { name: 'bike', keywords: ['bicycle', 'cycle', 'exercise', 'transport'] },
  { name: 'fuel', keywords: ['gas', 'petrol', 'station', 'car'] },

  // Shopping & Money
  { name: 'shopping-cart', keywords: ['buy', 'ecommerce', 'store', 'purchase'] },
  { name: 'shopping-bag', keywords: ['buy', 'retail', 'store', 'purchase'] },
  { name: 'shopping-basket', keywords: ['buy', 'grocery', 'store'] },
  { name: 'gift', keywords: ['present', 'birthday', 'surprise', 'reward'] },
  { name: 'tag', keywords: ['price', 'label', 'sale', 'category'] },
  { name: 'tags', keywords: ['price', 'labels', 'categories'] },
  { name: 'ticket', keywords: ['event', 'movie', 'admission', 'pass'] },
  { name: 'percent', keywords: ['discount', 'sale', 'math', 'percentage'] },
  { name: 'receipt', keywords: ['bill', 'purchase', 'invoice', 'payment'] },
  { name: 'credit-card', keywords: ['payment', 'money', 'bank', 'buy'] },
  { name: 'wallet', keywords: ['money', 'payment', 'cash', 'finance'] },
  { name: 'banknote', keywords: ['money', 'cash', 'currency', 'payment'] },
  { name: 'coins', keywords: ['money', 'cash', 'currency', 'payment'] },
  { name: 'piggy-bank', keywords: ['money', 'savings', 'bank', 'finance'] },
  { name: 'badge', keywords: ['label', 'status', 'achievement'] },
  { name: 'badge-check', keywords: ['verified', 'approved', 'certified'] },
  { name: 'badge-dollar-sign', keywords: ['money', 'price', 'cost'] },
  { name: 'package', keywords: ['box', 'delivery', 'shipping', 'parcel'] },
  { name: 'package-open', keywords: ['box', 'unbox', 'delivery'] },
  { name: 'box', keywords: ['package', 'container', 'storage'] },
  { name: 'boxes', keywords: ['packages', 'inventory', 'storage'] },

  // Communication
  { name: 'mail', keywords: ['email', 'message', 'letter', 'inbox'] },
  { name: 'mail-open', keywords: ['email', 'read', 'message'] },
  { name: 'mail-plus', keywords: ['email', 'new', 'compose'] },
  { name: 'inbox', keywords: ['email', 'messages', 'receive'] },
  { name: 'send', keywords: ['email', 'message', 'submit', 'paper plane'] },
  { name: 'message-circle', keywords: ['chat', 'comment', 'talk', 'bubble'] },
  { name: 'message-square', keywords: ['chat', 'comment', 'talk', 'bubble'] },
  { name: 'messages-square', keywords: ['chat', 'conversation', 'discussion'] },
  { name: 'phone', keywords: ['call', 'contact', 'mobile', 'telephone'] },
  { name: 'phone-call', keywords: ['call', 'ringing', 'incoming'] },
  { name: 'phone-incoming', keywords: ['call', 'receive', 'answer'] },
  { name: 'phone-outgoing', keywords: ['call', 'dial', 'outbound'] },
  { name: 'phone-missed', keywords: ['call', 'missed', 'voicemail'] },
  { name: 'phone-off', keywords: ['call', 'silent', 'mute'] },
  { name: 'bell', keywords: ['notification', 'alert', 'alarm', 'ring'] },
  { name: 'bell-off', keywords: ['notification', 'mute', 'silent'] },
  { name: 'bell-ring', keywords: ['notification', 'alert', 'alarm', 'ringing'] },
  { name: 'megaphone', keywords: ['announcement', 'speaker', 'broadcast', 'loud'] },
  { name: 'at-sign', keywords: ['email', 'mention', 'address'] },

  // Media & Entertainment
  { name: 'play', keywords: ['video', 'music', 'start', 'media'] },
  { name: 'pause', keywords: ['video', 'music', 'stop', 'media'] },
  { name: 'stop', keywords: ['video', 'music', 'end', 'media'] },
  { name: 'play-circle', keywords: ['video', 'music', 'start'] },
  { name: 'pause-circle', keywords: ['video', 'music', 'pause'] },
  { name: 'skip-back', keywords: ['video', 'music', 'previous', 'rewind'] },
  { name: 'skip-forward', keywords: ['video', 'music', 'next', 'forward'] },
  { name: 'rewind', keywords: ['video', 'music', 'back', 'reverse'] },
  { name: 'fast-forward', keywords: ['video', 'music', 'forward', 'speed'] },
  { name: 'volume', keywords: ['sound', 'audio', 'speaker'] },
  { name: 'volume-1', keywords: ['sound', 'audio', 'speaker', 'low'] },
  { name: 'volume-2', keywords: ['sound', 'audio', 'speaker', 'high'] },
  { name: 'volume-x', keywords: ['sound', 'mute', 'silent'] },
  { name: 'mic', keywords: ['microphone', 'audio', 'record', 'voice'] },
  { name: 'mic-off', keywords: ['microphone', 'mute', 'silent'] },
  { name: 'headphones', keywords: ['audio', 'music', 'listen'] },
  { name: 'speaker', keywords: ['audio', 'sound', 'music'] },
  { name: 'radio', keywords: ['audio', 'music', 'broadcast', 'fm'] },
  { name: 'music', keywords: ['audio', 'song', 'melody', 'note'] },
  { name: 'music-2', keywords: ['audio', 'song', 'melody', 'notes'] },
  { name: 'video', keywords: ['movie', 'film', 'record', 'camera'] },
  { name: 'video-off', keywords: ['movie', 'camera', 'disabled'] },
  { name: 'camera', keywords: ['photo', 'picture', 'image', 'capture'] },
  { name: 'camera-off', keywords: ['photo', 'disabled', 'no camera'] },
  { name: 'image', keywords: ['photo', 'picture', 'gallery'] },
  { name: 'images', keywords: ['photos', 'pictures', 'gallery'] },
  { name: 'film', keywords: ['movie', 'video', 'cinema'] },
  { name: 'clapperboard', keywords: ['movie', 'film', 'cinema', 'action'] },
  { name: 'tv', keywords: ['television', 'screen', 'watch', 'monitor'] },
  { name: 'monitor', keywords: ['screen', 'display', 'computer'] },
  { name: 'gamepad', keywords: ['game', 'play', 'controller', 'gaming'] },
  { name: 'gamepad-2', keywords: ['game', 'play', 'controller', 'gaming'] },
  { name: 'joystick', keywords: ['game', 'play', 'arcade', 'gaming'] },
  { name: 'puzzle', keywords: ['game', 'piece', 'solve', 'jigsaw'] },
  { name: 'dice-1', keywords: ['game', 'random', 'chance', 'gambling'] },
  { name: 'dice-2', keywords: ['game', 'random', 'chance', 'gambling'] },
  { name: 'dice-3', keywords: ['game', 'random', 'chance', 'gambling'] },
  { name: 'dice-4', keywords: ['game', 'random', 'chance', 'gambling'] },
  { name: 'dice-5', keywords: ['game', 'random', 'chance', 'gambling'] },
  { name: 'dice-6', keywords: ['game', 'random', 'chance', 'gambling'] },

  // Files & Documents
  { name: 'file', keywords: ['document', 'paper', 'page'] },
  { name: 'file-text', keywords: ['document', 'text', 'paper', 'page'] },
  { name: 'file-image', keywords: ['document', 'photo', 'picture'] },
  { name: 'file-video', keywords: ['document', 'movie', 'media'] },
  { name: 'file-audio', keywords: ['document', 'music', 'sound'] },
  { name: 'file-code', keywords: ['document', 'programming', 'dev'] },
  { name: 'file-plus', keywords: ['document', 'new', 'add', 'create'] },
  { name: 'file-minus', keywords: ['document', 'remove', 'delete'] },
  { name: 'file-x', keywords: ['document', 'delete', 'remove'] },
  { name: 'file-check', keywords: ['document', 'done', 'complete'] },
  { name: 'file-search', keywords: ['document', 'find', 'search'] },
  { name: 'files', keywords: ['documents', 'multiple', 'batch'] },
  { name: 'folder', keywords: ['directory', 'organize', 'files'] },
  { name: 'folder-open', keywords: ['directory', 'open', 'files'] },
  { name: 'folder-plus', keywords: ['directory', 'new', 'create'] },
  { name: 'folder-minus', keywords: ['directory', 'remove', 'delete'] },
  { name: 'folders', keywords: ['directories', 'organize', 'multiple'] },
  { name: 'archive', keywords: ['storage', 'backup', 'zip', 'compress'] },
  { name: 'clipboard', keywords: ['copy', 'paste', 'notes'] },
  { name: 'clipboard-copy', keywords: ['copy', 'duplicate'] },
  { name: 'clipboard-check', keywords: ['copy', 'done', 'complete', 'todo'] },
  { name: 'clipboard-list', keywords: ['tasks', 'todo', 'checklist'] },
  { name: 'book', keywords: ['read', 'library', 'study', 'education'] },
  { name: 'book-open', keywords: ['read', 'study', 'education', 'learn'] },
  { name: 'book-marked', keywords: ['read', 'bookmark', 'save'] },
  { name: 'bookmark', keywords: ['save', 'favorite', 'tag'] },
  { name: 'bookmarks', keywords: ['save', 'favorites', 'collection'] },
  { name: 'notebook', keywords: ['notes', 'write', 'journal'] },
  { name: 'library', keywords: ['books', 'read', 'collection'] },
  { name: 'newspaper', keywords: ['news', 'article', 'read', 'press'] },
  { name: 'scroll', keywords: ['document', 'ancient', 'paper'] },

  // Actions & UI
  { name: 'plus', keywords: ['add', 'new', 'create', 'increase'] },
  { name: 'plus-circle', keywords: ['add', 'new', 'create'] },
  { name: 'plus-square', keywords: ['add', 'new', 'create'] },
  { name: 'minus', keywords: ['remove', 'subtract', 'decrease'] },
  { name: 'minus-circle', keywords: ['remove', 'subtract', 'delete'] },
  { name: 'minus-square', keywords: ['remove', 'subtract', 'delete'] },
  { name: 'x', keywords: ['close', 'delete', 'remove', 'cancel'] },
  { name: 'x-circle', keywords: ['close', 'delete', 'error', 'cancel'] },
  { name: 'x-square', keywords: ['close', 'delete', 'remove'] },
  { name: 'check', keywords: ['done', 'complete', 'success', 'yes', 'correct'] },
  { name: 'check-circle', keywords: ['done', 'complete', 'success', 'verified'] },
  { name: 'check-square', keywords: ['done', 'complete', 'checkbox', 'todo'] },
  { name: 'circle', keywords: ['shape', 'dot', 'round'] },
  { name: 'square', keywords: ['shape', 'box', 'rectangle'] },
  { name: 'triangle', keywords: ['shape', 'warning', 'play'] },
  { name: 'pentagon', keywords: ['shape', 'polygon'] },
  { name: 'hexagon', keywords: ['shape', 'polygon', 'honeycomb'] },
  { name: 'octagon', keywords: ['shape', 'stop', 'polygon'] },
  { name: 'diamond', keywords: ['shape', 'gem', 'card'] },
  { name: 'more-horizontal', keywords: ['menu', 'options', 'dots', 'ellipsis'] },
  { name: 'more-vertical', keywords: ['menu', 'options', 'dots', 'ellipsis'] },
  { name: 'menu', keywords: ['hamburger', 'navigation', 'sidebar'] },
  { name: 'search', keywords: ['find', 'lookup', 'magnify', 'query'] },
  { name: 'zoom-in', keywords: ['search', 'magnify', 'enlarge'] },
  { name: 'zoom-out', keywords: ['search', 'magnify', 'shrink'] },
  { name: 'filter', keywords: ['sort', 'funnel', 'refine'] },
  { name: 'filter-x', keywords: ['sort', 'clear', 'remove filter'] },
  { name: 'settings', keywords: ['config', 'options', 'gear', 'preferences'] },
  { name: 'settings-2', keywords: ['config', 'options', 'sliders'] },
  { name: 'sliders', keywords: ['settings', 'adjust', 'config'] },
  { name: 'sliders-horizontal', keywords: ['settings', 'adjust', 'config'] },

  // Edit & Tools
  { name: 'edit', keywords: ['pencil', 'write', 'modify', 'change'] },
  { name: 'edit-2', keywords: ['pencil', 'write', 'modify'] },
  { name: 'edit-3', keywords: ['pencil', 'write', 'modify'] },
  { name: 'pen', keywords: ['write', 'draw', 'edit'] },
  { name: 'pen-tool', keywords: ['write', 'draw', 'design', 'vector'] },
  { name: 'pencil', keywords: ['write', 'draw', 'edit'] },
  { name: 'highlighter', keywords: ['mark', 'highlight', 'emphasis'] },
  { name: 'eraser', keywords: ['delete', 'remove', 'clear'] },
  { name: 'trash', keywords: ['delete', 'remove', 'garbage', 'bin'] },
  { name: 'trash-2', keywords: ['delete', 'remove', 'garbage', 'bin'] },
  { name: 'copy', keywords: ['duplicate', 'clipboard', 'paste'] },
  { name: 'scissors', keywords: ['cut', 'trim', 'snip'] },
  { name: 'save', keywords: ['disk', 'store', 'download'] },
  { name: 'download', keywords: ['save', 'get', 'arrow down'] },
  { name: 'upload', keywords: ['send', 'share', 'arrow up'] },
  { name: 'share', keywords: ['send', 'social', 'forward'] },
  { name: 'share-2', keywords: ['send', 'social', 'forward', 'network'] },
  { name: 'link', keywords: ['url', 'chain', 'connect', 'hyperlink'] },
  { name: 'link-2', keywords: ['url', 'chain', 'connect'] },
  { name: 'unlink', keywords: ['url', 'break', 'disconnect'] },
  { name: 'paperclip', keywords: ['attach', 'file', 'attachment'] },
  { name: 'wrench', keywords: ['tool', 'fix', 'repair', 'settings'] },
  { name: 'hammer', keywords: ['tool', 'build', 'construct'] },
  { name: 'screwdriver', keywords: ['tool', 'fix', 'repair'] },

  // Navigation & Arrows
  { name: 'arrow-up', keywords: ['direction', 'up', 'north'] },
  { name: 'arrow-down', keywords: ['direction', 'down', 'south'] },
  { name: 'arrow-left', keywords: ['direction', 'back', 'west', 'previous'] },
  { name: 'arrow-right', keywords: ['direction', 'forward', 'east', 'next'] },
  { name: 'arrow-up-circle', keywords: ['direction', 'up'] },
  { name: 'arrow-down-circle', keywords: ['direction', 'down'] },
  { name: 'arrow-left-circle', keywords: ['direction', 'back'] },
  { name: 'arrow-right-circle', keywords: ['direction', 'forward'] },
  { name: 'chevron-up', keywords: ['direction', 'expand', 'collapse'] },
  { name: 'chevron-down', keywords: ['direction', 'expand', 'collapse', 'dropdown'] },
  { name: 'chevron-left', keywords: ['direction', 'back', 'previous'] },
  { name: 'chevron-right', keywords: ['direction', 'forward', 'next'] },
  { name: 'chevrons-up', keywords: ['direction', 'fast', 'double'] },
  { name: 'chevrons-down', keywords: ['direction', 'fast', 'double'] },
  { name: 'chevrons-left', keywords: ['direction', 'fast', 'first'] },
  { name: 'chevrons-right', keywords: ['direction', 'fast', 'last'] },
  { name: 'move', keywords: ['drag', 'reorder', 'position'] },
  { name: 'maximize', keywords: ['fullscreen', 'expand', 'enlarge'] },
  { name: 'maximize-2', keywords: ['fullscreen', 'expand', 'resize'] },
  { name: 'minimize', keywords: ['shrink', 'collapse', 'reduce'] },
  { name: 'minimize-2', keywords: ['shrink', 'collapse', 'resize'] },
  { name: 'external-link', keywords: ['open', 'new tab', 'outside'] },
  { name: 'undo', keywords: ['back', 'reverse', 'history'] },
  { name: 'undo-2', keywords: ['back', 'reverse', 'history'] },
  { name: 'redo', keywords: ['forward', 'repeat', 'history'] },
  { name: 'redo-2', keywords: ['forward', 'repeat', 'history'] },
  { name: 'refresh-cw', keywords: ['reload', 'sync', 'update'] },
  { name: 'refresh-ccw', keywords: ['reload', 'sync', 'update'] },
  { name: 'rotate-cw', keywords: ['turn', 'spin', 'clockwise'] },
  { name: 'rotate-ccw', keywords: ['turn', 'spin', 'counter'] },
  { name: 'repeat', keywords: ['loop', 'cycle', 'again'] },
  { name: 'shuffle', keywords: ['random', 'mix', 'reorder'] },
  { name: 'navigation', keywords: ['location', 'direction', 'gps'] },
  { name: 'compass', keywords: ['direction', 'navigation', 'explore'] },
  { name: 'map', keywords: ['location', 'navigation', 'geography'] },
  { name: 'map-pin', keywords: ['location', 'marker', 'place'] },
  { name: 'locate', keywords: ['location', 'gps', 'position'] },
  { name: 'crosshair', keywords: ['target', 'aim', 'focus'] },

  // Security & Status
  { name: 'lock', keywords: ['security', 'password', 'private', 'closed'] },
  { name: 'lock-open', keywords: ['security', 'unlock', 'open'] },
  { name: 'unlock', keywords: ['security', 'open', 'access'] },
  { name: 'key', keywords: ['security', 'password', 'access', 'unlock'] },
  { name: 'key-round', keywords: ['security', 'password', 'access'] },
  { name: 'shield', keywords: ['security', 'protection', 'safe'] },
  { name: 'shield-check', keywords: ['security', 'verified', 'protected'] },
  { name: 'shield-alert', keywords: ['security', 'warning', 'danger'] },
  { name: 'shield-off', keywords: ['security', 'unprotected', 'vulnerable'] },
  { name: 'eye', keywords: ['view', 'see', 'show', 'visible', 'watch'] },
  { name: 'eye-off', keywords: ['hide', 'invisible', 'private', 'hidden'] },
  { name: 'fingerprint', keywords: ['security', 'biometric', 'identity'] },
  { name: 'scan', keywords: ['qr', 'barcode', 'capture'] },
  { name: 'qr-code', keywords: ['scan', 'barcode', 'link'] },
  { name: 'verified', keywords: ['check', 'approved', 'certified'] },
  { name: 'alert-circle', keywords: ['warning', 'error', 'danger', 'attention'] },
  { name: 'alert-triangle', keywords: ['warning', 'caution', 'danger'] },
  { name: 'alert-octagon', keywords: ['stop', 'error', 'danger'] },
  { name: 'info', keywords: ['information', 'help', 'about', 'details'] },
  { name: 'help-circle', keywords: ['question', 'support', 'faq'] },
  { name: 'ban', keywords: ['block', 'forbidden', 'no', 'prohibited'] },
  { name: 'circle-check', keywords: ['done', 'success', 'complete'] },
  { name: 'circle-x', keywords: ['error', 'failed', 'cancel'] },

  // Time & Calendar
  { name: 'clock', keywords: ['time', 'watch', 'schedule', 'hour'] },
  { name: 'timer', keywords: ['time', 'countdown', 'stopwatch'] },
  { name: 'timer-off', keywords: ['time', 'stop', 'pause'] },
  { name: 'stopwatch', keywords: ['time', 'timer', 'race'] },
  { name: 'alarm-clock', keywords: ['time', 'wake', 'reminder'] },
  { name: 'hourglass', keywords: ['time', 'wait', 'loading', 'sand'] },
  { name: 'calendar', keywords: ['date', 'schedule', 'event', 'month'] },
  { name: 'calendar-days', keywords: ['date', 'schedule', 'month', 'week'] },
  { name: 'calendar-check', keywords: ['date', 'event', 'done', 'scheduled'] },
  { name: 'calendar-plus', keywords: ['date', 'event', 'add', 'new'] },
  { name: 'calendar-x', keywords: ['date', 'event', 'cancel', 'remove'] },
  { name: 'calendar-range', keywords: ['date', 'period', 'span'] },
  { name: 'calendar-clock', keywords: ['date', 'time', 'schedule'] },
  { name: 'calendar-heart', keywords: ['date', 'love', 'anniversary', 'valentine'] },
  { name: 'history', keywords: ['time', 'past', 'recent', 'log'] },

  // Health & Medical
  { name: 'activity', keywords: ['health', 'pulse', 'heartbeat', 'chart'] },
  { name: 'stethoscope', keywords: ['health', 'doctor', 'medical', 'hospital'] },
  { name: 'syringe', keywords: ['health', 'medical', 'injection', 'vaccine'] },
  { name: 'pill', keywords: ['health', 'medical', 'medicine', 'drug'] },
  { name: 'tablets', keywords: ['health', 'medical', 'medicine', 'pills'] },
  { name: 'thermometer', keywords: ['health', 'temperature', 'fever', 'sick'] },
  { name: 'bandage', keywords: ['health', 'medical', 'injury', 'wound'] },
  { name: 'cross', keywords: ['health', 'medical', 'hospital', 'plus'] },
  { name: 'brain', keywords: ['health', 'mind', 'think', 'intelligence'] },
  { name: 'bone', keywords: ['health', 'skeleton', 'body', 'anatomy'] },
  { name: 'dna', keywords: ['health', 'science', 'genetics', 'biology'] },

  // Sports & Fitness
  { name: 'dumbbell', keywords: ['fitness', 'gym', 'exercise', 'workout', 'weight'] },
  { name: 'trophy', keywords: ['win', 'award', 'champion', 'competition'] },
  { name: 'medal', keywords: ['win', 'award', 'achievement', 'prize'] },
  { name: 'target', keywords: ['goal', 'aim', 'focus', 'bullseye'] },
  { name: 'swords', keywords: ['fight', 'battle', 'combat', 'game'] },
  { name: 'sword', keywords: ['fight', 'weapon', 'combat', 'game'] },
  { name: 'axe', keywords: ['tool', 'weapon', 'chop', 'wood'] },

  // Development & Code
  { name: 'code', keywords: ['programming', 'developer', 'html', 'brackets'] },
  { name: 'code-2', keywords: ['programming', 'developer', 'script'] },
  { name: 'terminal', keywords: ['code', 'command', 'shell', 'cli'] },
  { name: 'terminal-square', keywords: ['code', 'command', 'console'] },
  { name: 'command', keywords: ['keyboard', 'mac', 'shortcut'] },
  { name: 'binary', keywords: ['code', 'data', 'computer', 'digital'] },
  { name: 'braces', keywords: ['code', 'json', 'object', 'programming'] },
  { name: 'brackets', keywords: ['code', 'array', 'programming'] },
  { name: 'regex', keywords: ['code', 'pattern', 'search', 'programming'] },
  { name: 'variable', keywords: ['code', 'programming', 'data'] },
  { name: 'function-square', keywords: ['code', 'programming', 'method'] },
  { name: 'git-branch', keywords: ['code', 'version', 'control', 'branch'] },
  { name: 'git-commit', keywords: ['code', 'version', 'save'] },
  { name: 'git-merge', keywords: ['code', 'version', 'combine'] },
  { name: 'git-pull-request', keywords: ['code', 'version', 'pr', 'review'] },
  { name: 'git-fork', keywords: ['code', 'version', 'copy', 'clone'] },
  { name: 'github', keywords: ['code', 'git', 'repository', 'social'] },
  { name: 'gitlab', keywords: ['code', 'git', 'repository'] },
  { name: 'database', keywords: ['data', 'storage', 'server', 'sql'] },
  { name: 'server', keywords: ['computer', 'hosting', 'backend', 'api'] },
  { name: 'hard-drive', keywords: ['storage', 'disk', 'save', 'computer'] },
  { name: 'cpu', keywords: ['computer', 'processor', 'chip', 'hardware'] },
  { name: 'memory-stick', keywords: ['ram', 'computer', 'hardware'] },
  { name: 'circuit-board', keywords: ['hardware', 'electronics', 'computer'] },
  { name: 'bot', keywords: ['robot', 'ai', 'automation', 'chat'] },
  { name: 'webhook', keywords: ['api', 'automation', 'integration'] },
  { name: 'api', keywords: ['code', 'integration', 'endpoint'] },

  // Devices
  { name: 'laptop', keywords: ['computer', 'device', 'macbook', 'notebook'] },
  { name: 'laptop-2', keywords: ['computer', 'device', 'notebook'] },
  { name: 'smartphone', keywords: ['phone', 'mobile', 'device', 'iphone'] },
  { name: 'tablet', keywords: ['device', 'ipad', 'screen'] },
  { name: 'desktop', keywords: ['computer', 'screen', 'monitor'] },
  { name: 'keyboard', keywords: ['type', 'input', 'computer'] },
  { name: 'mouse', keywords: ['click', 'input', 'computer'] },
  { name: 'mouse-pointer', keywords: ['cursor', 'click', 'arrow'] },
  { name: 'printer', keywords: ['print', 'document', 'paper'] },
  { name: 'wifi', keywords: ['internet', 'wireless', 'network', 'connection'] },
  { name: 'wifi-off', keywords: ['internet', 'offline', 'disconnect'] },
  { name: 'bluetooth', keywords: ['wireless', 'connect', 'pair'] },
  { name: 'signal', keywords: ['network', 'connection', 'bars'] },
  { name: 'cast', keywords: ['screen', 'chromecast', 'airplay'] },
  { name: 'usb', keywords: ['port', 'connect', 'cable', 'storage'] },
  { name: 'plug', keywords: ['power', 'connect', 'cable', 'electric'] },

  // Miscellaneous
  { name: 'lightbulb', keywords: ['idea', 'light', 'bright', 'innovation', 'tip'] },
  { name: 'lightbulb-off', keywords: ['idea', 'dark', 'off'] },
  { name: 'lamp', keywords: ['light', 'desk', 'illuminate'] },
  { name: 'lamp-desk', keywords: ['light', 'work', 'office'] },
  { name: 'flashlight', keywords: ['light', 'torch', 'search'] },
  { name: 'party-popper', keywords: ['celebration', 'confetti', 'birthday', 'fun'] },
  { name: 'graduation-cap', keywords: ['education', 'school', 'degree', 'graduate'] },
  { name: 'glasses', keywords: ['vision', 'read', 'eyewear', 'see'] },
  { name: 'shirt', keywords: ['clothes', 'fashion', 'wear', 'tshirt'] },
  { name: 'watch', keywords: ['time', 'accessory', 'wrist', 'clock'] },
  { name: 'ruler', keywords: ['measure', 'size', 'length', 'tool'] },
  { name: 'scale', keywords: ['weight', 'measure', 'balance', 'justice'] },
  { name: 'magnet', keywords: ['attract', 'metal', 'physics'] },
  { name: 'brush', keywords: ['paint', 'art', 'design', 'draw'] },
  { name: 'palette', keywords: ['color', 'paint', 'art', 'design'] },
  { name: 'wand', keywords: ['magic', 'auto', 'enhance'] },
  { name: 'wand-2', keywords: ['magic', 'sparkle', 'enhance'] },
  { name: 'crown', keywords: ['king', 'queen', 'royal', 'premium', 'vip'] },
  { name: 'gem', keywords: ['diamond', 'jewel', 'precious', 'premium'] },
  { name: 'award', keywords: ['prize', 'achievement', 'badge', 'ribbon'] },
  { name: 'flag', keywords: ['country', 'mark', 'report', 'milestone'] },
  { name: 'infinity', keywords: ['forever', 'endless', 'loop', 'math'] },
  { name: 'ghost', keywords: ['halloween', 'spooky', 'boo', 'spirit'] },
  { name: 'skull', keywords: ['death', 'danger', 'halloween', 'skeleton'] },

  // Furniture & Home
  { name: 'bed', keywords: ['sleep', 'bedroom', 'rest', 'hotel'] },
  { name: 'sofa', keywords: ['furniture', 'couch', 'living room', 'sit'] },
  { name: 'armchair', keywords: ['furniture', 'chair', 'sit', 'relax'] },
  { name: 'bath', keywords: ['bathroom', 'wash', 'tub', 'clean'] },
  { name: 'cooking-pot', keywords: ['kitchen', 'food', 'cook', 'soup'] },

  // Auth & Account
  { name: 'log-in', keywords: ['signin', 'enter', 'access', 'auth'] },
  { name: 'log-out', keywords: ['signout', 'exit', 'leave', 'auth'] },
  { name: 'power', keywords: ['on', 'off', 'switch', 'button'] },
  { name: 'power-off', keywords: ['shutdown', 'off', 'close'] },
  { name: 'toggle-left', keywords: ['switch', 'off', 'disable'] },
  { name: 'toggle-right', keywords: ['switch', 'on', 'enable'] },

  // Charts & Social
  { name: 'bar-chart', keywords: ['data', 'graph', 'statistics', 'analytics'] },
  { name: 'bar-chart-2', keywords: ['data', 'graph', 'statistics'] },
  { name: 'pie-chart', keywords: ['data', 'graph', 'statistics', 'percentage'] },
  { name: 'line-chart', keywords: ['data', 'graph', 'trend', 'analytics'] },
  { name: 'trending-up', keywords: ['chart', 'growth', 'increase', 'positive'] },
  { name: 'trending-down', keywords: ['chart', 'decline', 'decrease', 'negative'] },
  { name: 'globe', keywords: ['world', 'internet', 'web', 'earth', 'international'] },
  { name: 'globe-2', keywords: ['world', 'earth', 'planet'] },
];

// Helper to convert kebab-case to PascalCase
export function toPascalCase(str: string): string {
  return str
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}
