import { NextRequest, NextResponse } from 'next/server';
import { createClient, createAdminClient } from '@/lib/supabase/server';
import type { CreateClassroomRequest, ClassroomWithDetails } from '@/lib/classroom/types';

/**
 * GET /api/classrooms
 * List classrooms for the current user (as teacher or student)
 */
export async function GET(request: NextRequest) {
  try {
    // Use regular client for auth, admin client for data queries (bypasses RLS)
    const authClient = await createClient();
    const supabase = createAdminClient();

    // Check authentication
    const {
      data: { user },
      error: authError,
    } = await authClient.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const role = searchParams.get('role'); // 'teacher' | 'student' | null (both)

    // Fetch classrooms where user is teacher
    let teacherClassrooms: ClassroomWithDetails[] = [];
    if (!role || role === 'teacher') {
      const { data, error } = await supabase
        .from('classrooms')
        .select(
          `
          *,
          teacher:profiles!classrooms_teacher_id_fkey(id, display_name, avatar_url)
        `
        )
        .eq('teacher_id', user.id)
        .eq('is_active', true)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Fetch teacher classrooms error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
      }

      // Add enrollment count for each classroom
      teacherClassrooms = await Promise.all(
        (data || []).map(async (classroom) => {
          const { count } = await supabase
            .from('classroom_enrollments')
            .select('*', { count: 'exact', head: true })
            .eq('classroom_id', classroom.id)
            .eq('status', 'active');

          const { count: assignmentCount } = await supabase
            .from('classroom_assignments')
            .select('*', { count: 'exact', head: true })
            .eq('classroom_id', classroom.id)
            .eq('is_active', true);

          return {
            ...classroom,
            enrollment_count: count || 0,
            assignment_count: assignmentCount || 0,
          };
        })
      );
    }

    // Fetch classrooms where user is enrolled as student
    let studentClassrooms: ClassroomWithDetails[] = [];
    if (!role || role === 'student') {
      const { data: enrollments, error: enrollError } = await supabase
        .from('classroom_enrollments')
        .select(
          `
          classroom_id,
          classroom:classrooms(
            *,
            teacher:profiles!classrooms_teacher_id_fkey(id, display_name, avatar_url)
          )
        `
        )
        .eq('student_id', user.id)
        .eq('status', 'active');

      if (enrollError) {
        console.error('Fetch student classrooms error:', enrollError);
        return NextResponse.json({ error: enrollError.message }, { status: 500 });
      }

      // Transform joined data (classroom comes as array from Supabase, extract first)
      studentClassrooms = (enrollments || [])
        .map((e) => {
          const classroom = Array.isArray(e.classroom) ? e.classroom[0] : e.classroom;
          if (!classroom) return null;
          // Also transform nested teacher array
          return {
            ...classroom,
            teacher: Array.isArray(classroom.teacher) ? classroom.teacher[0] : classroom.teacher,
          };
        })
        .filter((c): c is ClassroomWithDetails => c !== null && c.is_active);
    }

    return NextResponse.json({
      teaching: teacherClassrooms,
      enrolled: studentClassrooms,
    });
  } catch (error) {
    console.error('Classrooms fetch error:', error);
    return NextResponse.json({ error: 'Failed to fetch classrooms' }, { status: 500 });
  }
}

/**
 * POST /api/classrooms
 * Create a new classroom (teacher only)
 */
export async function POST(request: NextRequest) {
  try {
    // Use regular client for auth, admin client for data queries
    const authClient = await createClient();
    const supabase = createAdminClient();

    // Check authentication
    const {
      data: { user },
      error: authError,
    } = await authClient.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body: CreateClassroomRequest = await request.json();

    // Validate required fields
    if (!body.name || body.name.trim().length === 0) {
      return NextResponse.json(
        { error: 'Classroom name is required' },
        { status: 400 }
      );
    }

    // Create classroom (join_code is auto-generated by DB default)
    const { data: classroom, error: createError } = await supabase
      .from('classrooms')
      .insert({
        name: body.name.trim(),
        description: body.description?.trim() || null,
        teacher_id: user.id,
      })
      .select(
        `
        *,
        teacher:profiles!classrooms_teacher_id_fkey(id, display_name, avatar_url)
      `
      )
      .single();

    if (createError) {
      console.error('Create classroom error:', createError);

      // Handle unique constraint violation (rare, but possible with join_code)
      if (createError.code === '23505') {
        return NextResponse.json(
          { error: 'Please try again (code conflict)' },
          { status: 409 }
        );
      }

      return NextResponse.json({ error: createError.message }, { status: 500 });
    }

    return NextResponse.json(
      {
        ...classroom,
        enrollment_count: 0,
        assignment_count: 0,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Create classroom error:', error);
    return NextResponse.json({ error: 'Failed to create classroom' }, { status: 500 });
  }
}
