import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { createAdminClient } from '@/lib/supabase/server';
import { getStorageUrl } from '@/lib/utils';
import type { CardWithTerms, CardSong } from '@/lib/supabase/types';
import { JsonLd } from '@/components/JsonLd';
import { AudioPlayer } from '@/components/AudioPlayer';
import { CardActions } from '@/components/CardActions';
import { SongsSection } from '@/components/SongsSection';
import { LearnPageTracker } from '@/components/LearnPageTracker';
import { Header } from '@/components/Header';

interface PageProps {
  params: Promise<{ slug: string }>;
}

// Revalidate pages every 60 seconds to pick up new songs/changes
export const revalidate = 60;

// Generate static params for all cards (skip when env not set, e.g. at build time)
export async function generateStaticParams() {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return [];
  }
  const supabase = createAdminClient();
  const { data: cards } = await supabase.from('cards').select('slug');
  return (cards || []).map((card) => ({ slug: card.slug }));
}

// Dynamic metadata for SEO
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const card = await getCard(slug);

  if (!card) {
    return { title: 'Card Not Found - EZViet' };
  }

  const viTerm = card.terms?.find(t => t.lang === 'vi' && t.region === 'south');
  const enTerm = card.terms?.find(t => t.lang === 'en');

  const title = `How to say "${enTerm?.text}" in Vietnamese | EZViet`;
  const description = `Learn Vietnamese: "${enTerm?.text}" is "${viTerm?.text}" ${viTerm?.romanization ? `(pronounced /${viTerm.romanization}/)` : ''}. Free Vietnamese flashcards with audio.`;

  return {
    title,
    description,
    keywords: [
      viTerm?.text,
      enTerm?.text,
      'Vietnamese',
      'learn Vietnamese',
      'Vietnamese vocabulary',
      'Vietnamese flashcard',
      viTerm?.romanization,
    ].filter(Boolean) as string[],
    openGraph: {
      title,
      description,
      type: 'article',
      siteName: 'EZViet',
      // Image is auto-generated by opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Image is auto-generated by opengraph-image.tsx
    },
    alternates: {
      canonical: `https://ezviet.com/learn/${slug}`,
    },
  };
}

interface CardWithSongs extends CardWithTerms {
  songs: CardSong[];
}

async function getCard(slug: string): Promise<CardWithSongs | null> {
  const supabase = createAdminClient();

  const { data: card, error } = await supabase
    .from('cards')
    .select(`
      *,
      category:categories(*),
      terms:card_terms(*),
      songs:card_songs(*)
    `)
    .eq('slug', slug)
    .single();

  if (error || !card) return null;

  // Sort songs by sort_order
  if (card.songs) {
    card.songs.sort((a: CardSong, b: CardSong) => (a.sort_order ?? 0) - (b.sort_order ?? 0));
  }

  // Note: View count is now tracked client-side via LearnPageTracker
  // This ensures real user views are counted, not build-time renders

  return card as CardWithSongs;
}

export default async function LearnCardPage({ params }: PageProps) {
  const { slug } = await params;
  const card = await getCard(slug);

  if (!card) {
    notFound();
  }

  const viTermSouth = card.terms?.find(t => t.lang === 'vi' && t.region === 'south');
  const enTerm = card.terms?.find(t => t.lang === 'en');
  const imageUrl = getStorageUrl('cards-images', card.image_path);

  // JSON-LD Structured Data for SEO/AEO
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'LearningResource',
    name: `How to say "${enTerm?.text}" in Vietnamese`,
    description: `Vietnamese vocabulary: ${viTermSouth?.text} means ${enTerm?.text}`,
    learningResourceType: 'Flashcard',
    educationalLevel: 'Beginner',
    inLanguage: ['en', 'vi'],
    image: imageUrl,
    teaches: {
      '@type': 'DefinedTerm',
      name: viTermSouth?.text,
      description: `Vietnamese word for ${enTerm?.text}`,
      inDefinedTermSet: {
        '@type': 'DefinedTermSet',
        name: 'Vietnamese Vocabulary',
      },
    },
    provider: {
      '@type': 'Organization',
      name: 'EZViet',
      url: 'https://ezviet.org',
    },
  };

  return (
    <>
      {/* JSON-LD for AI/SEO - using safe component */}
      <JsonLd data={jsonLd} />

      {/* Track views and user learning progress */}
      <LearnPageTracker cardId={card.id} cardSlug={card.slug} />

      <main className="min-h-screen bg-background">
        <Header />

        {/* Card */}
        <div className="max-w-md mx-auto px-4 py-8">
          <article className="bg-(--surface-card) rounded-3xl shadow-xl overflow-hidden border border-(--border-default)">
            {/* Vietnamese Text */}
            <div className="pt-8 px-6 text-center">
              <h1 className="text-4xl font-bold text-foreground">
                {viTermSouth?.text}
              </h1>
              {viTermSouth?.romanization && (
                <p className="text-xl text-(--text-tertiary) mt-2">
                  /{viTermSouth.romanization}/
                </p>
              )}
              <div className="mt-3">
                <AudioPlayer
                  audioPath={viTermSouth?.audio_path}
                  text={viTermSouth?.text || ''}
                />
              </div>
            </div>

            {/* Image */}
            <div className="p-6">
              <div className="aspect-square bg-(--surface-elevated) rounded-2xl overflow-hidden flex items-center justify-center">
                <img
                  src={imageUrl}
                  alt={`${enTerm?.text} - ${viTermSouth?.text}`}
                  className="max-w-full max-h-full object-contain"
                />
              </div>
            </div>

            {/* English */}
            <div className="pb-8 px-6 text-center">
              <p className="text-2xl text-(--text-secondary)">{enTerm?.text}</p>
            </div>

            {/* Category */}
            {card.category && (
              <div className="bg-(--surface-elevated) px-6 py-3 text-center border-t border-(--border-default)">
                <span className="text-sm text-(--text-tertiary)">
                  {card.category.icon} {card.category.name}
                </span>
              </div>
            )}
          </article>

          {/* Actions: Print, Share, etc. */}
          <CardActions slug={slug} />

          {/* Learning Songs */}
          {card.songs && card.songs.length > 0 && (
            <SongsSection songs={card.songs} cardSlug={slug} />
          )}

          {/* Navigation */}
          <div className="mt-6 flex justify-center gap-4">
            <Link
              href="/"
              className="bg-(--interactive) hover:bg-(--interactive-hover) text-(--text-inverse) font-semibold px-8 py-3 rounded-xl transition-colors"
            >
              ← Learn More Words
            </Link>
          </div>

          {/* SEO Content */}
          <div className="mt-12 text-center text-(--text-secondary) text-sm space-y-2">
            <p>Learn how to say &quot;{enTerm?.text}&quot; in Vietnamese.</p>
            <p>
              The Vietnamese word for {enTerm?.text} is <strong className="text-foreground">{viTermSouth?.text}</strong>
              {viTermSouth?.ipa ? (
                <> <span className="text-(--text-tertiary)">[{viTermSouth.ipa}]</span></>
              ) : viTermSouth?.romanization ? (
                <> <span className="text-(--text-tertiary)">({viTermSouth.romanization})</span></>
              ) : null}.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
