-- Migration: Add AI generation tracking columns
-- Purpose: Support AI-powered auto-generation of Vietnamese translations
-- Date: 2024

-- ============================================
-- EXTEND CARD_TERMS TABLE
-- ============================================

-- Add phonetic helper (simplified pronunciation for English speakers)
-- e.g., "chwoy" for chuối
ALTER TABLE card_terms
ADD COLUMN IF NOT EXISTS phonetic_helper text;

-- Add IPA transcription (International Phonetic Alphabet)
-- e.g., "/tɕuoj˧˥/"
ALTER TABLE card_terms
ADD COLUMN IF NOT EXISTS ipa text;

-- Track if content was AI-generated
ALTER TABLE card_terms
ADD COLUMN IF NOT EXISTS generated_by_ai boolean DEFAULT false;

-- Track if admin has reviewed AI-generated content
ALTER TABLE card_terms
ADD COLUMN IF NOT EXISTS reviewed_by_admin boolean DEFAULT false;

-- Track which AI prompt version generated this content
-- Useful for re-generating with improved prompts later
ALTER TABLE card_terms
ADD COLUMN IF NOT EXISTS prompt_version text;

-- ============================================
-- EXTEND CARDS TABLE
-- ============================================

-- Add SEO meta description (AI-generated)
ALTER TABLE cards
ADD COLUMN IF NOT EXISTS meta_description text;

-- ============================================
-- INDEXES
-- ============================================

-- Partial index for finding unreviewed AI content
-- Only indexes rows where generated_by_ai = true (space efficient)
CREATE INDEX IF NOT EXISTS idx_card_terms_ai_unreviewed
ON card_terms(generated_by_ai, reviewed_by_admin)
WHERE generated_by_ai = true;

-- ============================================
-- COMMENTS (Documentation)
-- ============================================

COMMENT ON COLUMN card_terms.phonetic_helper IS
  'Simplified pronunciation guide for English speakers (e.g., "chwoy" for chuối)';

COMMENT ON COLUMN card_terms.ipa IS
  'IPA transcription with tones (e.g., /tɕuoj˧˥/)';

COMMENT ON COLUMN card_terms.generated_by_ai IS
  'True if this term was generated by AI';

COMMENT ON COLUMN card_terms.reviewed_by_admin IS
  'True if an admin has reviewed and approved AI-generated content';

COMMENT ON COLUMN card_terms.prompt_version IS
  'Version identifier for the AI prompt that generated this content (e.g., v1.0.0)';

COMMENT ON COLUMN cards.meta_description IS
  'SEO meta description for the card page (120-160 characters)';
